### ISSUE TITLE
[QUESTION] – What is this plugin for?

### ISSUE THREAD

**Issue by prot-cn** [CryptoMorin/XSeries#102]
Hello, Devs!
Please, interpret me about meaning of this plugin, also what kind main purpose to create it.
I really does not  mean: why should I use it? what is it doing?

Thanks.

**Comment by stijnb1234** [comment]
> Hello, Devs!
> Please, interpret me about meaning of this plugin, also what kind main purpose to create it.
> I really does not mean: why should I use it? what is it doing?
> 
> Thanks.

It's not a plugin. The library contains handy methods for supporting multiple versions in your MC plugins, as descripted in the Readme.

"Library mainly designed to provide cross-version support for Minecraft Bukkit servers, but it also includes numerous extra methods to help developers design their plugins easier and efficiently. Some utilities are completely unrelated to cross-version support such as NoteBlockMusic."

**Comment by itsxww** [comment]
Hey! Sorry for waiting, please. 
I am really glad that you've fast response rate.

Can you share here an example of useful using your library?

**Comment by CryptoMorin** [comment]
Have you checked the Spigot page? I'll give you an example for XItemStack:
```java
ItemStack item = XItemStack.deserialize(plugin.getConfig().getConfigurationSection("items.magic-sword"));
player.getInventory().addItem(item);
```

What this does is to use multiple utilities in this library (XMaterial, XEnchantment, ...) and make a single method out of them that you use to get items from the config in a cross-version compatible way that's not in an ugly format like the default `config.set("items.magic-sword", itemstack)` and is easier to manage with different shortcuts for server owners.

**Comment by itsxww** [comment]
As I understood, it gives help in write/read data on external resource.
Then I want to hear one more thing: does it support json format saving?

**Comment by itsxww** [comment]
As I understood, it gives help in write/read data on external resource.
Thankful!
