### ISSUE TITLE
[XMaterial] - 1.12 Piston parsed into Moving Piston instead

### ISSUE THREAD

**Issue by LOOHP** [CryptoMorin/XSeries#103]
**Description**
```java
XMaterial.matchXMaterial(item);
```
Using this line of code on a regular piston item in 1.12.2 matches into the XMaterial Moving Piston instead of the Piston

**Version**
Minecraft 1.12.2

**Comment by LOOHP** [comment]
Any update on this issue?

**Comment by CryptoMorin** [comment]
It's actually a really simple fix. I just haven't pushed the update to the repo yet. I think in a few days.

**Comment by LOOHP** [comment]
Thank you!

**Comment by CryptoMorin** [comment]
Fixed in **v7.9.0**
