### ISSUE TITLE
[XMaterial] - parseMaterial() and parseItem() stained glasses issues

### ISSUE THREAD

**Issue by Darrionat** [CryptoMorin/XSeries#104]
**Description**
Using `XMaterial.BLACK_STAINED_GLASS_PANE.parseMaterial()` actually gets `Material.WHITE_STAINED_GLASS_PANE`.
Within my gui, when I use XMaterials that would hold a byte/id value within older versions, it appears that it returns the default material. This is including wool, glass, etc.

Using `XMaterial.BLACK_STAINED_GLASS_PANE.parseItem()` within 1.8.8 works just fine, but in 1.16.5 it does not function properly.

However, `XMaterial.BLACK_STAINED_GLASS_PANE.parseMaterial()` in both 1.8.8 and 1.16.5 does not actually get the correct Material of `Material.BLACK_STAINED_GLASS_PANE`. 

**Version**
I'm currently using 7.8.0 of XSeries
Tested on both Spigot 1.16.5 and on Spigot 1.8.8

**Comment by CryptoMorin** [comment]
> **Description**
> Using `XMaterial.BLACK_STAINED_GLASS_PANE.parseMaterial()` actually gets `Material.WHITE_STAINED_GLASS_PANE`.
> Within my gui, when I use XMaterials that would hold a byte/id value within older versions, it appears that it returns the default material. This is including wool, glass, etc.

This is intended for 1.12 and below. You have to use `parseItem()`

> Using `XMaterial.BLACK_STAINED_GLASS_PANE.parseItem()` within 1.8.8 works just fine, but in 1.16.5 it does not function properly.

Please define "does not function properly"

> However, `XMaterial.BLACK_STAINED_GLASS_PANE.parseMaterial()` in both 1.8.8 and 1.16.5 does not actually get the correct Material of `Material.BLACK_STAINED_GLASS_PANE`.

I'm unable to reproduce this for 1.16.5, I'm exactly getting `BLACK_STAINED_GLASS_PANE`
And it's intended for 1.8.8 like mentioned above.

**Comment by Darrionat** [comment]
> This is intended for 1.12 and below. You have to use parseItem()
Even with `parseItem()` I'm still not obtaining the correct type of pane in 1.16.5. 

Code: 
`for (int i = 0; i < size; i++) {
	inv.setItem(i, XMaterial.BLACK_STAINED_GLASS_PANE.parseItem());
}`
Output: ![wrong_glass_type](https://user-images.githubusercontent.com/52856180/108637118-2bc15780-7457-11eb-870c-97a6a9ae1afc.png)

And even if I `parseMaterial()` and create an item from that material, I'm not obtaining the correct type.

> Please define "does not function properly"
To define "does not function properly," I am speaking in the context that the returned type from both `parseMaterial()` and `parseItem()` not getting the correct type of item for me. 
My 1.16.5 server is running `CraftBukkit version git-Spigot-73fb609-0cd8f19 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT`

**Comment by CryptoMorin** [comment]
The problem is I can't reproduce it.

**Comment by Darrionat** [comment]
`The problem is I can't reproduce it.`

I'm not sure how you can't. What server version are you using?

When I did some more testing on my 1.16 server, here are some interesting results I have obtained. 

When I do `p.sendMessage(XMaterial.BLACK_STAINED_GLASS_PANE.parseMaterial().toString());`
I receive the following result `STAINED_GLASS_PANE`

And when I do `p.sendMessage(XMaterial.BLACK_STAINED_GLASS_PANE.parseItem().toString());`
I receive the following `ItemStack{LEGACY_STAINED_GLASS_PANE x 1}`

I'm still quite unsure as to why this is happening, and I would love more feedback, and perhaps a more efficient manner to discuss this if you'd like so as well.

**Comment by CryptoMorin** [comment]
I'm also using 1.16.5 `git-Paper-449 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
The only thing I can think of is:
1. You didn't specify `api-version: 1.13` in your `plugin.yml`
2. The build you're using is bugged.

**Comment by Darrionat** [comment]
> You didn't specify api-version: 1.13 in your plugin.yml

Ah yes, this is it.
