### ISSUE TITLE
Add unit test for each utility class.

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#109]

**Comment by portlek** [comment]
- https://github.com/seeseemelk/MockBukkit
- https://github.com/mockito/mockito
- https://github.com/powermock/powermock

**Comment by CryptoMorin** [comment]
The first one sounds really useful. Should I just write all the test units in a single ignored class with separate method? I don't think making a whole package with multiple separate test units going to be that useful.

**Comment by CryptoMorin** [comment]
Wait, there's a problem. How would I add multiple unit tests for multiple versions?

**Comment by portlek** [comment]
There is a tricky way but I'm not sure you OK with putting NMS repository from codemc to create test for each spigot version.

**Comment by CryptoMorin** [comment]
Actually the current repo is codemc. So sure, go ahead.

**Comment by portlek** [comment]
Alright, I will create a P.R. to show an example for it.
