### ISSUE TITLE
[ParticleDisplay] - 1.8 Compatibility

### ISSUE THREAD

**Issue by GabrielAtlas** [CryptoMorin/XSeries#117]
**Description**
I want to display helix effect with the ParticleDisplay object but org.bukkit.Particle class not exists in the 1.8 JAR
A lib xyz.xenondevs.particle.ParticleEffect solves the Reflection process to display particles and can be the ParticleDisplay compatibillity easier for yours

Thanks, Jon.

**Version**
Minecraft Spigot Version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
XSeries version 7.9.1.1

**Comment by CryptoMorin** [comment]
I considered 1.8 compatibility for particles before. Since it's the only troublesome version and requires a lot of changes, I personally do not want to change the system just for a single outdated version.
