### ISSUE TITLE
[1.17 Support] - Add 1.17 support for the XSeries library

### ISSUE THREAD

**Issue by Skyslycer** [CryptoMorin/XSeries#121]
**Description**
Please add support for 1.17, I really want to update my plugin.
Thank you very much <3

**Comment by Skyslycer** [comment]
Never did anything, I am dumb...

**Comment by CryptoMorin** [comment]
Please do not do this to any other developer in the future whether it's a plugin, a server software, mod, completely Minecraft unrelated and etc.
They generally find it annoying. You can't expect them to do it within the first few days of the main program release (tho I managed without updating the NMS)
I'm just saying this for your own sake.

**Comment by Skyslycer** [comment]
Thats what I noticed and thats why I closed this issue...
