### ISSUE TITLE
[XMaterial] - Issue

### ISSUE THREAD

**Issue by PeachesMLG** [CryptoMorin/XSeries#122]
In the latest version you changed the enum GRASS_PATH to DIRT_PATH to reflect spigot's changes, 
```
DIRT_PATH(new String[]{"GRASS_PATH"}),
```
Wouldnt it make more sence to keep the enum name the same and make DIRT_PATH as an alias for compatibility reasons? I store a running total of all blocks on an island in the database and this is causing errors
https://imgur.com/6WaSdPm.png

**Comment by LOOHP** [comment]
I believe having DIRT_PATH with GRASS_PATH being an alias is the way to go. XMaterial always reflect the changes of the latest Minecraft version.

**Comment by CryptoMorin** [comment]
And that is why there is a `matchXMaterial()`
