### ISSUE TITLE
[Support modded block] - Remplace enum XMaterial by normal class

### ISSUE THREAD

**Issue by Romaindu35** [CryptoMorin/XSeries#126]
**Description**
By default, XSeries don't support modded block because the enumerations are not editable. To support modded blocks, the enumeration should be replaced by a normal class.

**Comment by CryptoMorin** [comment]
As a reminder what this library is for:
> Library for cross-version Minecraft **Bukkit** support 

Spigot also uses enums, so I don't really understand what you mean.
Converting enums to classes is just a nightmare and a torture.

It's almost as hard as writing a class builder based on the enum. So I think you're okay with writing on yourself?
If you ever did, post it here. I'll add it to the wiki.

**Comment by Romaindu35** [comment]
If you want, I can make this change and do a pull request

**Comment by CryptoMorin** [comment]
You can write any kind of class you want, I just won't be maintaining it. It'll go in the wiki section for people who are willing to update it themselves.
