### ISSUE TITLE
Feature: Create tags for releases

### ISSUE THREAD

**Issue by josephjthomas** [CryptoMorin/XSeries#128]
**Description**
A clear and concise description of what the feature is.
Support for versions older than 1.8 will not be added. Some projects might not even support 1.8

I see you commit changes starting new versions like here: https://github.com/CryptoMorin/XSeries/commit/edc46105a0544439e81753e1aa9dde1609a983e9
To maintain and mange my dependency on my projects, I often use tools like dependabot. That's a GitHub bot that notifies you about dependency updates and creates pull requests for them showing a list of changes, but has a lot of other useful functionality as well:
![](https://i.imgur.com/hXcLJLa.png)
Therefore it's necessary to tag a commit (better known as "Releases" on GitHub) with the version same like you do in your commit messages.
I would kindly like to ask if that could be done for future releases, that would make everyone's workflow a bit easier who uses such tools to maintain their dependencies.
Kind regards

**Comment by CryptoMorin** [comment]
> Therefore it's necessary to tag a commit (better known as "Releases" on GitHub)

"Tags" and "Releases" are too different concept as far as I know. The only similarity is that releases are based on tags.
Sure I'll consider doing that for future releases.

**Comment by josephjthomas** [comment]
Thanks for looking into it!

**Comment by CryptoMorin** [comment]
There we go! Our first release. [8.3.0](https://github.com/CryptoMorin/XSeries/releases/tag/v8.3.0)
