### ISSUE TITLE
[FEATURE] - 1.8 compatibility

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#13]
**Description**
These methods:

https://github.com/CryptoMorin/XSeries/blob/master/XPotion.java#L259
https://github.com/CryptoMorin/XSeries/blob/master/XPotion.java#L293

are not compatible with **1.8-1.10** versions. There is not a method called `setColor` in the Meta.

**Comment by CryptoMorin** [comment]
I can just set it to use raw RGB integers. Thanks for letting me know.

**Comment by portlek** [comment]
```
XBlock
XEnchantment
XEntity
XItemStack
XPotion
XSound
ZEnchantment
```
This classes are not compatibility with 1.8 version.

**Comment by portlek** [comment]
For example:

![image](https://user-images.githubusercontent.com/12835420/73139373-7dde5080-407e-11ea-95ad-a28deddf0014.png)
![image](https://user-images.githubusercontent.com/12835420/73139375-8e8ec680-407e-11ea-84bf-af52c947542b.png)
![image](https://user-images.githubusercontent.com/12835420/73139379-96e70180-407e-11ea-9b99-0d668e875d99.png)

**Comment by CryptoMorin** [comment]
You're supposed to compile with the latest version of Spigot. Notice the **ISLFAT** boolean check.
As long as an unknown reference in the code is not executed it'll not cause any errors.

The last one is correct, but XEntity doesn't support 1.8 (for now)

**Comment by CryptoMorin** [comment]
After looking further for 1.8 Potion colors it's not possible with the Bukkit API, only 1.9+
With that being said, the method will not change.
