### ISSUE TITLE
[FEATURE] - There is not a library.

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#14]
**Description**
There should be a pom.xml(maven project) for adding libraries automatically. Because we have to add external `.jar` file to the project and this situation cause little problem for people who're contributing to the project.

**Comment by CryptoMorin** [comment]
The only library is Bukkit tho. You should import the Bukkit/Spigot Jar itself not from maven.
Even if I gave you the pom file you still need to import Spigot for mojang authlib.

**Comment by portlek** [comment]
There is
```xml
<repository>
    <id>nms-repo</id>
    <url>https://repo.codemc.org/repository/nms/</url>
</repository>
<dependency>
    <groupId>org.spigotmc</groupId>
    <artifactId>spigot</artifactId>
    <version>1.15-R0.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```
codemc spigot jar with authlib.

**Comment by CryptoMorin** [comment]
I only use the original Spigot repository.
