### ISSUE TITLE
1.18 Support

### ISSUE THREAD

**Issue by PeachesMLG** [CryptoMorin/XSeries#147]
Didnt know if there was a discord or anything for XSeries, so ill just ask here.

Is anyone currently working on 1.18 support? Doesnt look like there are that many changes: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/compare/diff?targetBranch=d32e3c764edd6a449ddd220720185d266c2193f9&sourceBranch=refs%2Fheads%2Fmaster&targetRepoId=11

**Comment by LOOHP** [comment]
I would be happy to create a PR. However, I am unsure what approach XSeries is going to take in dealing with biome changes so I guess we'll have to wait.

**Comment by CryptoMorin** [comment]
Please do not make issues regarding new Minecraft versions. It will happen, but creating an issue about it for every single version doesn't help.

And don't make any PRs either.
> Do not make PRs relating to adding support when a new version of Minecraft comes out. I'll be finishing the update within the first week of Spigot release. Multiple developers working on the same thing will be just a waste of time and resources.

from [contributing guidelines](https://github.com/CryptoMorin/XSeries/blob/master/CONTRIBUTING.md).
