### ISSUE TITLE
[ReflectionUtils] - NoSuchFieldException 1.17 playerConnection field

### ISSUE THREAD

**Issue by NewZAZ** [CryptoMorin/XSeries#148]
**Description**
The problem happens when I open my gui and when I use the SkullUtils and I don't know why 
https://pastebin.com/bz6MMZDy

**Version**
1.17

**Comment by Lorenzo0111** [comment]
Same error with reflection utils

**Comment by SwartZCoding** [comment]
Same error too on 1.17

**Comment by divios** [comment]
Same with me, seems to be a "warning" since all works as expected

**Comment by SwartZCoding** [comment]
> Same with me, seems to be a "warning" since all works as expected

He stop the opening of my menu personnaly. So i think it's a error ^^.

**Comment by CryptoMorin** [comment]
It's a critical error for all reflection-based utilities yes and the fix is rather simple. I'm just finishing some unit tests before I release.

**Comment by divios** [comment]
Great, thanks for the quick response!. I may also go ahead and take a look at your unit test for inspiration since I wanted to do some for my plugins but I have no idea how to.

**Comment by SwartZCoding** [comment]
> It's a critical error for all reflection-based utilities yes and the fix is rather simple. I'm just finishing some unit tests before I release.

Great, thanks for your quick response ! I look forward to the fix.

**Comment by CryptoMorin** [comment]
This should be patched in v8.5.0.1
