### ISSUE TITLE
[Material Parsing] - Issue

### ISSUE THREAD

**Issue by CoderBoyo** [CryptoMorin/XSeries#151]
**Description**
When I try to parse an XMaterial ex: GREEN_STAINED_GLASS_PANE the result is a regular white glass pane even on versions that support those materials. This happens for a lot of Materials similar to this.

**Version**
The plugin supports all versions 1.8-1.18 however in this case the server is running on 1.12.2. 
(Incase it matters I'm using ViaVersion and connecting with 1.17.1)

**Comment by CryptoMorin** [comment]
You didn't show any code.
