### ISSUE TITLE
[XPotion] - Spigot 1.12.2 initialization error

### ISSUE THREAD

**Issue by pkuliyi2015** [CryptoMorin/XSeries#158]
**Description**
When directly call XPotion.matchXPotion(String potion) on spigot 1.12.2, the code report an initialization error. The following code reports NPE:
    static {
        for (XPotion pot : VALUES) POTIONEFFECTTYPE_MAPPING[pot.type.getId()] = pot;
    }

The stacktrace has only one line:
 pku.yim.magicblock.libs.xseries.XPotion.<clinit>(XPotion.java:120)

I do relocation but I think it shouldn't be the problem. I carefully investigate your code, and guess it's because the pot.type is null, and

 XPotion(@Nonnull String... aliases) {
        this.type = PotionEffectType.getByName(this.name()); // will be null in legacy versions!
        Data.NAMES.put(this.name(), this);
        for (String legacy : aliases) Data.NAMES.put(legacy, this);
    }

**Version**
Spigot 1.12.2, XSeries 8.6.0

I love your XSeries library, and hope it can be even more popular!

**Comment by CryptoMorin** [comment]
Fixed in 8.6.1

**Comment by CryptoMorin** [comment]
Sorry I don't have one :P
