### ISSUE TITLE
[XPotion] - INSTANT_DAMAGE value missing

### ISSUE THREAD

**Issue by cervinakuy** [CryptoMorin/XSeries#159]
**Description**
INSTANT_DAMAGE is missing from XPotion (causes errors on 1.8.8 specifically). It should be a simple addition of "INSTANT_DAMAGE" on this line:
https://github.com/CryptoMorin/XSeries/blob/a719a4d063af5f4b2edf5daabd1226f36e78ba46/src/main/java/com/cryptomorin/xseries/XPotion.java#L72

**Version**
Spigot 1.8.8, XSeries 8.6.0

**Comment by CryptoMorin** [comment]
Fixed in 8.6.1
