### ISSUE TITLE
XMaterial - Hard_Clay material conversion issue

### ISSUE THREAD

**Issue by GavvyDizzle** [CryptoMorin/XSeries#160]
If you use
```XMaterial.matchXMaterial(new ItemStack(Material.HARD_CLAY))```
or
```XMaterial.matchXMaterial("Hard_Clay")```
it will return "Clay" instead of "Terracotta"

Tested in version 1.12.2 ^

Clay is listed as ```CLAY("HARD_CLAY")```
Terracotta is listed as ```TERRACOTTA("STAINED_CLAY")```

In 1.12, uncolored terracotta is listed as Material.HARD_CLAY.

Shouldn't clay be listed as ```Clay```,
and terracotta as ```TERRACOTTA("HARD_CLAY")```?

**Comment by CryptoMorin** [comment]
You're right, fixed in v8.6.2
