### ISSUE TITLE
[Issue] - Can't compile with java 17

### ISSUE THREAD

**Issue by VoChiDanh** [CryptoMorin/XSeries#161]
**Description**
When i run package with java 17
> Unsupported class file major version 61

![image](https://user-images.githubusercontent.com/86956269/154405353-332c5389-a6f7-42dc-93f0-a5948dc2e68a.png)

**Version**
Paper-API 1.18.1
Maven 
![image](https://user-images.githubusercontent.com/86956269/154405480-ca0952d7-ebbe-4eba-8d7c-1302e48c75ba.png)

**Comment by HSGamer** [comment]
Try to set the project Java version to something lower than Java 16 (recommend Java 11).
The shade plugin v3.2.4 does not support Java 16 and cause the error.

**Comment by HSGamer** [comment]
Add this to pom.xml
```xml
<pluginRepositories>
    <pluginRepository>
        <id>maven-snapshots</id>
        <url>https://repository.apache.org/content/repositories/snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```
and change the version of `maven-shade-plugin` to `3.3.0-SNAPSHOT`

**Comment by VoChiDanh** [comment]
> Add this to pom.xml
> 
> ```
> <pluginRepositories>
>     <pluginRepository>
>         <id>maven-snapshots</id>
>         <url>https://repository.apache.org/content/repositories/snapshots/</url>
>     </pluginRepository>
> </pluginRepositories>
> ```
> 
> and change the version of `maven-shade-plugin` to `3.3.0-SNAPSHOT`

Thanks bro
