### ISSUE TITLE
[XTag] - XTag.isItem(XMaterial material) Reports NPE

### ISSUE THREAD

**Issue by pkuliyi2015** [CryptoMorin/XSeries#168]
**Description**
The XTag.isItem directly use XMaterial.parseMaterial().isItem() without checking the parseMaterial() is null or not.

Example stacktrace:
java.lang.NullPointerException
[18:27:40 WARN]:        at pku.yim.magicblock.libs.xseries.XTag.isItem(XTag.java:2017)
[18:27:40 WARN]:        at pku.yim.magicblock.block.Block.parseMaterials(Block.java:171)

Problematic code:
public static boolean isItem(XMaterial material) {
        if (XMaterial.supports(13)) return material.parseMaterial().isItem();
...
}

**Note**
Any chain invokes like this will lead to the same NPE when the XMaterial doesn't have a corresponding Bukkit Material in the older version. So, you may need to check the following two methods:
XTag.isItem
XTag.isInteractable
...

**Version**
purpur 1.16.5
XSeries 8.7.0

**Comment by CryptoMorin** [comment]
Fixed in v8.7.1
