### ISSUE TITLE
[XBlock] - Comparing data on <1.13

### ISSUE THREAD

**Issue by Wertik** [CryptoMorin/XSeries#172]
**Description**

I've noticed that methods like [XBlock#isSimilar(Block, XMaterial)](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XBlock.java#L599) only compare the block type and ignore raw byte data on versions <1.13. I think it would be useful to either have a method that does this, or modify #isSimilar to do so.

Example:
(Version 1.8)
```java
// Load a material from config or somewhere to match, let's say LIME_WOOL
XMaterial xMaterial = XMaterial.matchXMaterial("LIME_WOOL");
```

```java
// If the player mines LIME_WOOL (WOOL, data: 5), something happens..
if (XBlock.isSimilar(event.getBlock(), xMaterial) {
  // Something happens...
}
```
With the current #isSimilar, this would match any type (color in this case) of wool. This seems like an unexpected behaviour given there's no alternative.

[XBlock#getType(Block)](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XBlock.java#L567) seemed like a way to go, but it has been deprecated. I realize there's probably a good reason behind that. However, is there anything wrong about the following solution?

(XBlock#compareType for ex.)
```java
@SuppressWarnings("deprecation")
public static boolean compareType(Block block, XMaterial material) {
    XMaterial blockMaterial = XMaterial.matchXMaterial(block.getType());

    if (blockMaterial != material) {
        return false;
    }

    return ISFLAT || block.getData() == material.getData();
}
```
This would match flattened types on 1.13, as well as raw byte data on <1.13.

I tried to do my research, if I missed anything I'm sorry.

**Comment by CryptoMorin** [comment]
Block's raw data is affected by several factors that are not considered as a Material distinguishing factor. For example the direction that stairs are facing is encoded in the data value. Or they're mixed, you can put down wood blocks differently so you have wood type and its direction mixed as a bit flag pattern.
