### ISSUE TITLE
XMaterial - Has no "WODDEN_BUTTON" in OAK_BUTTON

### ISSUE THREAD

**Issue by andrew121410** [CryptoMorin/XSeries#175]
**Description**
1.12.2 has wooden_button yet that's missing in XMaterial OAK_BUTTON

**Version**
Running 1.18.2 on XSeries 8.7.1

**Comment by CryptoMorin** [comment]
Seems like `DARK_OAK_BUTTON` is also using `WOOD_BUTTON` (`OAK_BUTTON` is using that too) which is either wrong it has a data value that I didn't put, not sure.

**Comment by andrew121410** [comment]
Oh never mind it’s actually correct. I apologize
