### ISSUE TITLE
Planned Removal of commons-lang

### ISSUE THREAD

**Issue by handy-git** [CryptoMorin/XSeries#177]
Planned Removal of commons-lang
As foreshadowed with the 1.18 release, commons-lang has now been removed from the API. Plugins will not yet be broken as it is still included with the server, however it will eventually be removed in a future release. Please consider switching to Google Guava (which is a supported bundled API) or using your own copy of the much more recent commons-lang3.

**Comment by CryptoMorin** [comment]
I'm mostly using Apache Commons for it's `StringUtils` and `WordUtils` does Google's Guava have anything similar to `StringUtils.deleteWhitespace` and `WordUtils.capitalize`?

**Comment by CryptoMorin** [comment]
Fixed in v9.0.0
