### ISSUE TITLE
Titles - Bug

### ISSUE THREAD

**Issue by NeonnDev** [CryptoMorin/XSeries#180]
**Description**
I have updated all XSeries files and still have the bug that the subtitle is the same as the title.
This error does not appear under 1.19.

**Version**
1.19

**Comment by CryptoMorin** [comment]
I need a reproducible code (altho it may obviously simple) and your exact server version.

**Comment by CryptoMorin** [comment]
Next time if you had the same issue reopen, this issue, don't make a new one. And when you do make any issues, make sure to also provide the things I asked you above.
