### ISSUE TITLE
Incorrect XMaterial matched from ItemStack

### ISSUE THREAD

**Issue by I2000C** [CryptoMorin/XSeries#188]
**Description**
In Minecraft 1.8 (it's possible that in Minecraft 1.9-1.12 this happens too) there are 2 flower items that will map to incorrect XMaterial.
These items are RED_ROSE:4 and RED_ROSE:6, so they should be mapped to RED_TULIP and WHITE_TULIP.
However, they are actually mapped to POTTED_RED_TULIP and POTTED_WHITE_TULIP so when I load the items again, a null value is returned since in legacy Minecraft version there is no item called "POTTED_RED_TULIP" or "POTTED_WHITE_TULIP".

I think this happens due to XMaterial enum order because in these two items the "POTTED" constant is before the "NOT-POTTED".
With the other flowers the "NOT-POTTED" constant is before the "POTTED" constant.

For example:
- POTTED_RED_TULIP is in line 1037 and RED_TULIP is in line 1147
- POTTED_WHITE_TULIP is in line 1041 and WHITE_TULIP is in line 1409
- POTTED_ORANGE_TULIP is in line 1032 and ORANGE_TULIP is in line 933
- POTTED_PINK_TULIP is in line 1034 and PINK_TULIP is in line 970

I believe this could happen with other materials.

**Version**
Minecraft version: 1.8.8 (latest Minecraft 1.8)

**Comment by CryptoMorin** [comment]
Potted flower materials shouldn't map to **RED_ROSE** in the first place. This was left from the material suggestion system that was removed before.

**Comment by CryptoMorin** [comment]
Fixed in v9.1.0
