### ISSUE TITLE
[XMaterial] - REGEX Pattern returning 0 matches for Crucible 1.7.10

### ISSUE THREAD

**Issue by MrKelpy** [CryptoMorin/XSeries#189]
Server Version: Crucible 1.7.10 / Spigot 1.7.10
XSeries Version: Latest

XMaterial doesn't seem to work for a Crucible/Spigot 1.7.10 server. The issue seems to stem from the static ctor in the Data class, that uses this Regex: 
`Matcher matcher = Pattern.compile("MC: \\d\\.(\\d+)").matcher(version);`

Regex Test: https://regex101.com/r/IgM19l/1

**Comment by CryptoMorin** [comment]
This library is not intended to work with 1.7
