### ISSUE TITLE
[XMaterial] - RED_DYE not found on 1.8.8

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#19]
**Description**
XMaterial.RED_DYE can't parse with `parseMaterial` method. It's returning null.

**Version**
1.8.8

**Comment by CryptoMorin** [comment]
Yeah, I already fixed this. Replace it with **RED_DYE(1, "INK_SACK", "ROSE_RED"),**
I'm waiting for 1.16 to come out.
