### ISSUE TITLE
[XMaterial] - Unable to match dyes on version 1.13.2

### ISSUE THREAD

**Issue by LOOHP** [CryptoMorin/XSeries#190]
**Description**
Dyes on 1.13.2, such as `ROSE_RED` or `DANDELION_YELLOW` cannot be matched on Minecraft version 1.13.2.
```
java.lang.IllegalArgumentException: Unsupported material from item: ROSE_RED (0)
java.lang.IllegalArgumentException: Unsupported material from item: DANDELION_YELLOW (0)
```
Dyes got renamed to `<COLOR>_DYE` on 1.14 and from then onwards it matches just fine.

**Version**
1.13.2

**Comment by CryptoMorin** [comment]
Fixed in v9.1.0

Please in the future add more context. There are many ways to "match" a material. Providing a reproduce code is helpful.
