### ISSUE TITLE
XMaterial - Issue

### ISSUE THREAD

**Issue by refrainsmc** [CryptoMorin/XSeries#191]
**Description**
`XMaterial.matchXMaterial(new ItemStack(Material.MELON_BLOCK)).name()` returns 'MELON_SLICE'. The expected result is 'MELON'.

**Version**
1.8.8

**Comment by CryptoMorin** [comment]
In case anyone looks at this in the future, the solution is `XMaterial.MELON_BLOCK.parseItem()`

**Comment by refrainsmc** [comment]
The issue seemed to be with the Spigot API or my implementation because I was trying to get translate the clicked item into an XMaterial and store the name into my MySQL database, and it was storing MELON_SLICE so I thought XMaterial was returning the wrong name.
