### ISSUE TITLE
[XMaterial] - Cocoa Beans Issue

### ISSUE THREAD

**Issue by LuckyKuka** [CryptoMorin/XSeries#193]
**Description**
Hello, I've got an issue with cocoa beans, when it's time for my randomizer to show cocoa beans I see this error in my console:

_org.bukkit.event.EventException: null_

_Caused by: java.lang.NullPointerException_
	_at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[server.jar:git-Spigot-21fe707-741a1bd]_
	_at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[server.jar:git-Spigot-21fe707-741a1bd]_
	_at mc.obliviate.inventory.Icon.<init>(Icon.java:34) ~[?:?]_

Also, you do not see cocoa beans in the GUI because of this error, please help.

**Note:** I do not use viaversion or protocols

**Version**
Latest Spigot 1.8.8

**Comment by CryptoMorin** [comment]
That's not enough information. I need the full error message and your code.

**Comment by LOOHP** [comment]
What is `Icon` and what does the `addItem` method do?

Besides, you don't need to share all of your code, just share a few lines that are able to produce your error, preferably with code that everybody already knows. (i.e. bukkit methods, XSeries methods)

**Comment by CryptoMorin** [comment]
I'm closing this issue because of insufficient information.
