### ISSUE TITLE
[XMaterial] - Parse material return incorrect material.

### ISSUE THREAD

**Issue by reussy** [CryptoMorin/XSeries#194]
**Description**
I've been using the library for a while, specifically more XMaterial, but now it fails to deliver the desired material (at least in older versions like 1.8).

I'm trying to use "PLAYER_HEAD" to get the player's skull with its texture but the material is always "SKULL" (skeleton skull).

![image](https://user-images.githubusercontent.com/63428864/198177487-4484a477-5569-45a4-8c27-ce9bffda6712.png)

Version: v9.1.0
Code:

```
public Material parseMaterial(String material) {

        if (material != null) {
            XMaterial xMaterial = XMaterial.matchXMaterial(material.toUpperCase()).orElse(XMaterial.STONE);
            return xMaterial.parseMaterial();
        }
        return null;
    }
```

🎯 **Important Note**: If I use something like XMaterial.PLAYER_HEAD.parseItem() it does return the material of a player head. I'm probably using the wrong method, but as I said above, I always did it this way and it worked without problems.

![image](https://user-images.githubusercontent.com/63428864/198178018-6909de49-94ee-4587-acaa-0a6e52ee74c2.png)

I am not sure if this is caused by other plugins, I have tried on different servers and the same problem.

**Version**
Server Version: 1.8.8

![image](https://user-images.githubusercontent.com/63428864/198177430-07261710-32a8-4cd6-921b-4cebed850a65.png)

**Comment by HSGamer** [comment]
Surely because `parseItem` does not just change the material, it also change the durability of the item.

**Comment by CryptoMorin** [comment]
Like mentioned above, if you need an ItemStack, you _have to_ use `parseItem()`. As you can see in your own screenshot the data values for the items are different.
