### ISSUE TITLE
[XItemStack] - Schulker box deserialized without items 

### ISSUE THREAD

**Issue by PrideIsLife** [CryptoMorin/XSeries#197]
**Description**
- Latest version of utility 💹 
- Minecraft `1.19.2`

Since a recent version, I couldn't tell which. Deserialized shulker boxes spawn as empty and do not contains the items listed under the `shulker` configuration key.

Exemple of serialized shulker : 
```
{
   "material":"SHULKER_BOX",
   "shulker":{
      "0":{
         "material":"LEATHER"
      },
      "1":{
         "material":"DIRT"
      },
      "2":{
         "material":"DEEPSLATE_GOLD_ORE",
         "name":"DEEPSLATE_GOLD_ORE"
      },
      "3":{
         "material":"WHEAT_SEEDS",
         "amount":2
      }
   }
}
```

The code I use to serialize items : 
```
Document(XItemStack.serialize(itemStack))
```

And for the desialization : 
```
returnedStack = XItemStack.deserialize(this.documentData)
```

ps: This code worked before like a charm.

**Comment by CryptoMorin** [comment]
This was fixed in the last commit.
