### ISSUE TITLE
[XBlock] - Does not recognize crops

### ISSUE THREAD

**Issue by Skjolberg** [CryptoMorin/XSeries#202]
Hello!

I am trying to know if a material is a crop, whatever the server version, the case is that when I break a crop such as wheat, it indicates that it is not a crop, but others like Carrot or Potato if it works, I have noticed that the IDs with full name like "CARROT", "POTATO" work, but instead the IDs with characters like "_" do not work, such as "MELON_STEM", "PUMPKIN_STEM", I comment it in case it has something to do with it.

I have performed this test in 1.8.8, clean server
Simple Code:

        XMaterial mat = XMaterial.matchXMaterial(event.getBlock().getType());
        if(XBlock.isCrop(mat)) {
            System.out.println(event.getBlock().getType());
            System.out.println(mat);
            System.out.println("Is crop");

        } else {
            System.out.println(event.getBlock().getType());
            System.out.println(mat);
            System.out.println("No crop");

        }

Example in console:

`[13:19:22 INFO]: PUMPKIN_STEM`
`[13:19:22 INFO]: Pumpkin Stem`
`[13:19:22 INFO]: No crop`

`[13:19:15 INFO]: CARROT`
`[13:19:15 INFO]: Carrot`
`[13:19:15 INFO]: Is crop`

`[13:31:21 INFO]: CROPS`
`[13:31:21 INFO]: Wheat`
`[13:31:21 INFO]: No crop`

As indicated here, it should work: [XBlock](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XBlock.java#L57)

If there is more information you would like to know just let me know. :)

**Comment by CryptoMorin** [comment]
Seems like the `CROPS` list simply doesn't have those materials. So just adding them to the list should fix that. Any other materials other than `MELON_STEM` and `PUMPKIN_STEM`?

**Comment by Skjolberg** [comment]
> Seems like the `CROPS` list simply doesn't have those materials. So just adding them to the list should fix that. Any other materials other than `MELON_STEM` and `PUMPKIN_STEM`?

Note that from versions like 1.12 to 1.13 they change the names like NETHER_WARTS -> NETHER_WART, and so on with several names, so I don't know all the ones that change and possibly affect the recognition of whether it is crop or not.

I have a switch case with the following xSeries enum and it has worked for me.

CARROTS:
POTATOES:
WHEAT:
PUMPKIN_STEM:
MELON_STEM:
BEETROOTS:
BAMBOO:
KELP_PLANT:
CARROT:
POTATO:
WHEAT_SEEDS:
PUMPKIN_SEEDS:
MELON_SEEDS:
BEETROOT_SEEDS:
BAMBOO_SAPLING:
KELP:
NETHER_WART:
SUGAR_CANE:
CHORUS_PLANT:
SEA_PICKLE:
BROWN_MUSHROOM:
RED_MUSHROOM:

**Comment by CryptoMorin** [comment]
Fixed in v9.3.0
