### ISSUE TITLE
[XEntity] - Cannot use isUndead on 1.8

### ISSUE THREAD

**Issue by KojiV** [CryptoMorin/XSeries#204]
So I was using XEntity#isUndead for redoing the enchantment system for Minecraft, and upon using said method, I got a NoSuchFieldError. I got it to work through separate means, but I felt like reporting this.

Server Version: 1.8.8 Paper

Returned by console:
`Caused by: java.lang.NoSuchFieldError: SKELETON_HORSE`
        `at koji.developerkit.utils.xseries.XEntity.<clinit>(XEntity.java:71) ~[?:?]`
        `at koji.skyblock.item.enchants.enchants.Smite.onSkyblockDamage(Smite.java:48) ~[?:?]`
        `at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]`
        `at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]`
        `at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]`
        `at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]`
        `at koji.skyblock.item.enchants.Enchant.runEvent(Enchant.java:60) ~[?:?]`
        `at koji.skyblock.player.GenericListeners.lambda$runFunction$0(GenericListeners.java:94) ~[?:?]`
        `at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]`
        `at koji.skyblock.player.GenericListeners.runFunction(GenericListeners.java:92) ~[?:?]`
        `at koji.skyblock.player.GenericListeners.runFunction(GenericListeners.java:54) ~[?:?]`
        `at koji.skyblock.player.MiscListeners.onSkyblockDamage(MiscListeners.java:135) ~[?:?]`
        `at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source) ~[?:?]`
        `at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]`
        `at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]`
        `at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]`

**Comment by CryptoMorin** [comment]
Strange that skeleton horses were added in v1.6 but they weren't available until v1.11
Fixed in v9.3.0
