### ISSUE TITLE
[Titles] - NoSuchFieldException on MC 1.20.1

### ISSUE THREAD

**Issue by Demeng7215** [CryptoMorin/XSeries#215]
**Description**
A NoSuchFieldException is thrown when using the Titles utility with Minecraft server version 1.20.1 (Pufferfish).
Stack trace: https://pastebin.com/3rXTi6Vm
Code: https://github.com/Demeng7215/PluginBase/blob/master/pluginbase-core/src/main/java/dev/demeng/pluginbase/menu/MenuManager.java#L121

**Version**
MC 1.20.1, XSeries v4.9.0

**Comment by CryptoMorin** [comment]
You're using XSeries **v4.9.0**? Did you mean **v9.4.0**? If so, that's still certainly not true, because your error shows otherwise. Either that or you're not actually running this on MC v1.20.1

**Comment by Demeng7215** [comment]
Whoops— it was a shading issue on my end. Sorry for the inconvenience.
