### ISSUE TITLE
[XItemStack] - CreatureSpawner without entity specified

### ISSUE THREAD

**Issue by david-morales-denox** [CryptoMorin/XSeries#216]
**Description**
`java.lang.NullPointerException: Cannot invoke "String.toUpperCase(java.util.Locale)" because the return value of "org.bukkit.configuration.ConfigurationSection.getString(String)" is null
        at com.cryptomorin.xseries.XItemStack.edit(XItemStack.java:646) ~[?:?]
        at com.cryptomorin.xseries.XItemStack.deserialize(XItemStack.java:381) ~[?:?]`
        
I receive this error, and looking into XItemStack code, i see its not checking if "spawner" value exists in the configuration section.
Because I have a SPAWNER material but without "spawner" specified, I think its better to set a default Entity if this not exists.

![image](https://github.com/CryptoMorin/XSeries/assets/108263680/3811651f-57e6-45f1-ac89-9c8bccdf35e6)

**Comment by CryptoMorin** [comment]
Fixed in v9.6.0
