### ISSUE TITLE
XTitles - MC 1.11 Failure

### ISSUE THREAD

**Issue by SwordOfSouls** [CryptoMorin/XSeries#217]
**Description**
When using server version 1.11 and sending a title 
`Caused by: java.lang.NoSuchMethodError: 'void org.bukkit.entity.Player.sendTitle(java.lang.String, java.lang.String, int, int, int)'
        at com.cryptomorin.xseries.messages.Titles.sendTitle(Titles.java:155) ~[?:?]`

**Version**
1.11

**Comment by CryptoMorin** [comment]
This is because the server is an outdated 1.11, but I fixed this in v9.6.0
