### ISSUE TITLE
[XMaterial] - How match material color types

### ISSUE THREAD

**Issue by reussy** [CryptoMorin/XSeries#218]
**Description**
What would be the correct usage to get the correct material from this type of enums / names?

Example:
I want to get the correct YELLOW_DYE material for version 1.8.9, according to the documentation and Javadocs I can use XMaterial.matchXMaterial(INK_SACK:11).parseMaterial(); but this always returns INK_SACK.

I have applied the same code in Wiki to debug this and got the following:

```txt
Matched(YELLOW_DYE) -> Optional[Yellow Dye], parsed: INK_SACK, suggestion: INK_SACK
```

```java
private final List<Material> DYES = List.of(
            XMaterial.YELLOW_DYE.parseMaterial(),
            XMaterial.matchXMaterial("DANDELION_YELLOW").get().parseMaterial());
```

![image](https://github.com/CryptoMorin/XSeries/assets/63428864/d4a36701-b026-4794-ada2-6c91c9f5ba94)

Is there any way to do this correctly or could it be a bug?

**Version**
Server Version: 1.8.9
XSeries Version: Latest

Regards

**Comment by CryptoMorin** [comment]
You have to use parseItem()
