### ISSUE TITLE
Continuous integration and test.

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#22]
We can add tests for each utility class. To do that, we need maven project, so maybe you don't want to add it but i think we should. Travis too.

**Comment by CryptoMorin** [comment]
This is a maven project tho? Also, I don't see why we need CI. Utilities are rarely changed and I do most of the updates which are fully tested.

**Comment by portlek** [comment]
I mean there is no pom.xml file and it's not maven project offically.

**Comment by CryptoMorin** [comment]
Well, there you go https://github.com/CryptoMorin/XSeries/blob/master/pom.xml
