### ISSUE TITLE
[XMaterial] - RED_MUSHROOM not found on 1.8.8

### ISSUE THREAD

**Issue by Pirgosth** [CryptoMorin/XSeries#23]
**Description**
XMaterial.RED_MUSHROOM return null when using `parseItem` method.
It seems like there's an issue with duplicated keys.

**Version**
1.8.8

**Comment by CryptoMorin** [comment]
Looks like just removing it from the duplicated list fixes the issue.

**Comment by Pirgosth** [comment]
Okay, but in this case what's the point of this duplicated list?

**Comment by CryptoMorin** [comment]
In this case, that's a bug. The duplicated list is only for materials that duplicate each other.
**RED_MUSHROOM_BLOCK** is indeed a duplicate of **RED_MUSHROOM** but not the other way around. Some complicated stuff.

**Comment by Pirgosth** [comment]
Ok, I fixed it by adding RED_MUSHROOM("RED_MUSHROOM") in the enum, but it's just a workaround, would you be able to fix it ?

**Comment by CryptoMorin** [comment]
> 
> 
> Looks like just removing it from the duplicated list fixes the issue.

That's literally the solution.

**Comment by Pirgosth** [comment]
Ok, so we can close this ticket ?
