### ISSUE TITLE
[ReflectionUtils] - PATCH_NUMBER does not contain correct value

### ISSUE THREAD

**Issue by stijnb1234** [CryptoMorin/XSeries#233]
**Description**
The PATCH_NUMBER field does not contain what's explained in the JavaDoc. For example, for version 1.19.2, it should be 1 (v1_19_R1), but it's 2 instead (from 1.19.2-R0.1-SNAPSHOT).

**Version**
1.19.2

**Comment by CryptoMorin** [comment]
I think it's just a misunderstanding. It's referring to the [Semantic Versioning](https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning) scheme.

```hs
1.19.2
     ^ Patch
```

**Comment by stijnb1234** [comment]
Yes, but the JavaDoc mentions:
`E.g. {@code v1_17_R1} to {@code 1}`

It shows the NMS version v1_17_R1, which for 1.19.2 would be `v1_19_R1`, but it returns patch 2.

**Comment by CryptoMorin** [comment]
Both v1.17.1 and v1.17.0 NMS versions are `v1_17_R1`. I can clarify it with more examples in the docs, sure.

**Comment by stijnb1234** [comment]
> Both v1.17.1 and v1.17.0 NMS versions are `v1_17_R1`. I can clarify it with more examples in the docs, sure.

Well, `v1_17_R1` implies it's the NMS patch, but that's not correct. It's the Minecraft (Bukkit) server patch. That's the problem I'm encountering.

Something like: `E.g. {@code 1.19.2-R0.1-SNAPSHOT} to {@code 2}` would be more clear.

**Comment by CryptoMorin** [comment]
Fixed in v9.8.0
