### ISSUE TITLE
[FALSE POSITIVE NOTIFY] - Weird update on Virus Total database

### ISSUE THREAD

**Issue by thefrogline** [CryptoMorin/XSeries#236]
Hi,  I’ve been using XSeries for a long time and I have no doubt that it’s very good and also safe, as it’s even open source. However, I work on plugin commissions, and I’ve been using XSeries for a year now, but just this week several people have been unable to download what I do, as it’s flagged as a virus. I tried removing all the libraries, and I realized that it came from XSeries. I mainly wanted to confirm if everything is okay with the library and so on. I attach evidence of the same jar, only removing the XSeries.
![image](https://github.com/CryptoMorin/XSeries/assets/76601496/0b269aeb-44c4-405a-acfc-a82e079a6e6f)
![image](https://github.com/CryptoMorin/XSeries/assets/76601496/2c3f157c-9e68-4974-b69e-04793e332369)

![image](https://github.com/CryptoMorin/XSeries/assets/76601496/715280fb-05a8-46b9-a6a3-4b7ee47eed41)
![image](https://github.com/CryptoMorin/XSeries/assets/76601496/c219a3bd-fee0-46a5-80c9-49984a045380)

(maybe it comes from something else, I don't think so, but hey, sorry if it's nonsense but it's something to know haha)

maven version:
    <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
            <version>9.3.1</version>
        </dependency>

edit: with last version (9.6.0) happens the same issue

**Comment by CryptoMorin** [comment]
The Log4J vulnerability warning has nothing to do with XSeries, because it doesn't even log anything.
As for Java Trojan warnings, the plugin does not access any of system's APIs, even files (except for NoteBlockMusic and XParticle classes)
So I don't know where to even look to diagnose the issue.

**Comment by LOOHP** [comment]
My plugins that use this library also got flagged as malware and some of my users are understandably concerted. Once upon a time when I used method handles instead of reflection I also triggered some antivirus. So it might be some code that could have accessed system resources but wasn't used for that purpose.

**Comment by CryptoMorin** [comment]
My main plugin other than XSeries, also uses a lot of system APIs and extreme reflection to mess with class loaders and other "suspicious-looking" code, but VirusTotal is totally (no pun intended) fine with it. It's not obfuscated.

https://www.virustotal.com/gui/file/f4b703e21e1e06d9c7604f28e1dbb73597eb5141f630cbba674f7445b5939ca2/detection

**Comment by thefrogline** [comment]
Hello, I was able to find an antivirus that gives me the path of the problem (windows defender only told me the name), I just looked and compared it with the repo code, it shows that it is a false positive, I don't see anything honestly strange, I'll still leave the photo here in case you want to review
![image](https://github.com/CryptoMorin/XSeries/assets/76601496/80d5675d-6b49-4018-af2d-ac63e6a1fc00)

**Comment by CryptoMorin** [comment]
> Hello, I was able to find an antivirus that gives me the path of the problem (windows defender only told me the name), I just looked and compared it with the repo code, it shows that it is a false positive, I don't see anything honestly strange, I'll still leave the photo here in case you want to review ![image](https://private-user-images.githubusercontent.com/76601496/285563871-80d5675d-6b49-4018-af2d-ac63e6a1fc00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTkzODIsIm5iZiI6MTcwMDkxOTA4MiwicGF0aCI6Ii83NjYwMTQ5Ni8yODU1NjM4NzEtODBkNTY3NWQtNmI0OS00MDE4LWFmMmQtYWM2M2U2YTFmYzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDEzMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTdhZDdkMDBiNTQ3MDZmYTMwNTE4NmM1NjFiMTg2ZjFjYmNlM2RmNjBhYjA0Y2ZmNGRkOGUzN2UwZjVmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wyoGAbiMYMWoXBRy4T6LKdwcBOP2hyZgi4oEvYm8GNo)

That's very interesting. Could you please name the anti virus that you used? Also, would it be possible to exclude XSound from being shaded to see if switches to detecting another class?

If it failed, try copy pasting XSound directly to your own project instead of shading it to see if it still detects it.

I don't know what separates that class from others. Maybe the CompletableFuture usage?

**Comment by thefrogline** [comment]
Hello, sorry for the delay, the antivirus is: "BitDefender" has a free version and it is the same, and do you think you can tell me how to exclude shaded, please?

**Comment by CryptoMorin** [comment]
> Hello, sorry for the delay, the antivirus is: "BitDefender" has a free version and it is the same, and do you think you can tell me how to exclude shaded, please?

It's in the [readme](https://github.com/CryptoMorin/XSeries#apache-maven-shade-plugin) page.
For SkullUtils it'd be
```xml
<exclude>com/cryptomorin/xseries/SkullUtils*</exclude>
```

**Comment by LOOHP** [comment]
Now it seems to be the switch statment in `isItem(material)` in `XTag` which is causing false positives. This is from the source file `XTag$1.class`, which when removed from XSeries-9.7.0.jar stops it from being flagged.

https://www.virustotal.com/gui/file/ab72a4c20c91848f62f1dfb57f72be1e58d978eda8439cfa5e750a2c762c6dcf

**Comment by CryptoMorin** [comment]
I'm really unsure why it'd flag that method specifically. Because there are other methods that use even longer switch statements like that.

**Comment by LOOHP** [comment]
I believe this can be closed now as it is no longer triggering positives in the latest version.

**Comment by CryptoMorin** [comment]
Huh, that's weird. That's great to hear tho. Thanks for checking.
