### ISSUE TITLE
[ItemBuilder] - Feature

### ISSUE THREAD

**Issue by Mr-EmPee** [CryptoMorin/XSeries#237]
**Description**
Class to easily build custom itemstack like [ItemBuilder](https://github.com/Mr-EmPee/ItemBuilder)

**Comment by CryptoMorin** [comment]
I'm personally in favor of letting people to fully configure all items. That's why I have XItemStack for that and no ItemBuilder.

**Comment by Mr-EmPee** [comment]
wdym by fully configure? With an item-builder you can choose what properties an itemstack is going to have
