### ISSUE TITLE
[XMaterial] - ParseMaterial/ParseItem does not return the right material/itemStack for Banner

### ISSUE THREAD

**Issue by Pirgosth** [CryptoMorin/XSeries#24]
**Description**
XMaterial.BLUE_BANNER or any other banner color does not return the right material, resulting in an exception when trying to get the associated BannerMeta.

`(org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.BannerMeta)`

**Version**
1.8.8

**Comment by CryptoMorin** [comment]
Use this for now https://pastebin.com/NfMgvAXt

**Comment by Pirgosth** [comment]
Ok thanks, I'll try thisi patch and keep you informed

**Comment by RoinujNosde** [comment]
> Use this for now https://pastebin.com/NfMgvAXt

@CryptoMorin I'm having a similar problem. parseItem is returning STANDING_BANNER on 1.8. And this pastebin can't be found (404).

**Comment by CryptoMorin** [comment]
Please open a new ticket. This issue was closed months ago. I also need need your code.
