### ISSUE TITLE
[XSound] - "java.lang.NoClassDefFoundError: org/bukkit/SoundCategory" on 1.8.8

### ISSUE THREAD

**Issue by cervinakuy** [CryptoMorin/XSeries#242]
**Description**
Hello, I'm the developer of [KitPvP](https://www.spigotmc.org/resources/27107/). KitPvP has used XSeries for years at this point - thank you for everything you do.

Anyway, I've been receiving multiple reports of this error on 1.8.8: https://pastebin.com/5ThHiNRy

Code references:
- [pom.xml: KitPvP is on the latest XSeries version (9.9.0)](https://github.com/cervinakuy/KitPvP/blob/905369d4caba2f7ad12b86441c4b8a319d277cee/pom.xml#L137)
- [HitListener.java: where XSound's Record is being used](https://github.com/cervinakuy/KitPvP/blob/905369d4caba2f7ad12b86441c4b8a319d277cee/src/main/java/com/planetgallium/kitpvp/listener/HitListener.java#L17)

At a glance, SoundCategory indeed does not exist in [Spigot 1.8.8](https://helpch.at/docs/1.8.8/), so the error does seem to make sense. I would imagine XSound is accidentally loading SoundCategory-related code when it shouldn't be (e.g. 1.8.8 version or greater, where SoundCategory does not exist).

**Version**
In the particular pastebin I've provided, Paper Spigot 1.8.8. I suppose this problem could also apply to versions >= 1.8.8 where SoundCategory also does not exist.

**Comment by CryptoMorin** [comment]
Yes, it looks like SoundCategory was introduced in v1.11 I'll fix it

**Comment by cervinakuy** [comment]
Hi, any updates on this?

I'm still receiving messages about this issue from plugin users, and unfortunately, it seems the error prevents the plugin from loading/enabling at all. If helpful, it seems another consumer of XSeries/XSound developed [a fix](https://github.com/FairyProject/fairy/commit/37bc18e0c9e0a3b7049c14c24b71ca45ca48b738), maybe it could serve as a starting point.

**Comment by CryptoMorin** [comment]
I'm sorry for the late reply. I was away for a while. It's fixed in v9.10.0 now.
