### ISSUE TITLE
Paper Support post removing CraftBukkit relocation

### ISSUE THREAD

**Issue by PeachesMLG** [CryptoMorin/XSeries#243]
**Description**
After paper removes CraftBukkit relocation (https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/) certain features will break in XSeries Namely https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/ReflectionUtils.java#L84

Which gets the version by using reflection to see the package name

**Comment by CryptoMorin** [comment]
Duplicate of https://github.com/CryptoMorin/XSeries/issues/240
