### ISSUE TITLE
[XMaterial] - The deprecated class org.bukkit.potion.Potion is no longer in use.

### ISSUE THREAD

**Issue by handy-git** [CryptoMorin/XSeries#245]
1.20.5  [spigotmc](https://www.spigotmc.org/threads/spigot-bungeecord-1-20-5.645069/)

The deprecated/legacy potion APIs, Potion and PotionData have been removed. Use the other classes available in the org.bukkit.potion package since Minecraft 1.9 / 2016.

**Comment by CryptoMorin** [comment]
Fixed in v10.0.0
