### ISSUE TITLE
XEnchantment - 1.20.5 Enchantment Name Changes

### ISSUE THREAD

**Issue by BGHDDevelopment** [CryptoMorin/XSeries#246]
**Description**
Hey all. With the release of 1.20.5, XEnchantment will need to be updated to match the changes.
"Enchantments...have been renamed to match their Minecraft name/key (tbc)."
Example: DIG_SPEED is now EFFICIENCY

**Version**
1.20.5

**Comment by CryptoMorin** [comment]
Fixed in v10.0.0
