### ISSUE TITLE
[XItemStack] - PDC alternatives for versions that doesn't support it

### ISSUE THREAD

**Issue by Mr-EmPee** [CryptoMorin/XSeries#249]
**Description**
Add cross-compatible method that allows for storing data inside an item, newer versions have the pdc API

**Comment by CryptoMorin** [comment]
I have my own personal library which is basically a version based on EngineHub's Lin Bus NBT handler. The scale and scope of such project is kind of out of place for XSeries. I might release a separate project in the future.
