### ISSUE TITLE
[XEnchantment] - NoSuchFieldError

### ISSUE THREAD

**Issue by ImYenil** [CryptoMorin/XSeries#253]
Description
When using XSeries 10.0.0 on Spigot 1.8.8, XEnchantment does not work properly and gives this stack trace: https://pastebin.com/VzU94YFc

    public ItemBuilder enchant(String enchantment, int level) {
        Enchantment xEnchantment = XEnchantment.matchXEnchantment(enchantment).orElse(XEnchantment.UNBREAKING).getEnchant();

        itemMeta.addEnchant(xEnchantment, level, true);

        return this;
    }

Version
XSeries 10.0.0, Paper 1.8.8

**Comment by datatags** [comment]
That code snippet works fine for me on those versions, are you sure you're shading and relocating XSeries properly in your plugin? Maybe another plugin on your server has shaded an older version of XSeries without relocation, so the server uses the older version
