### ISSUE TITLE
[XSkull] - Inconsistent behavior in different server versions & online/offline servers based on usernames and UUIDs

### ISSUE THREAD

**Issue by Condordito** [CryptoMorin/XSeries#254]
**Description**

At the moment, applying textures does not work correctly in multiple versions. Each one has slightly different behaviors. This issue was previously discussed in another post, but no further details were given on the topic (#235)

#### 1.12 (Online Server)
When applying a meta to an item stack, it generates the textures only if its GameProfile has a defined name or its UUID is stored in the server cache. Compared to the rest, the textures are applied synchronously, before being placed in an inventory

![Online 1 12](https://github.com/CryptoMorin/XSeries/assets/48872538/fa66f2b1-16d0-4071-a9e9-ed2401c4930e)

<img width="1026" alt="Screenshot 2024-05-15 at 1 48 03 AM" src="https://github.com/CryptoMorin/XSeries/assets/48872538/11fb28d9-051d-46a7-a3dc-74ec3d24d6eb">

<img width="1004" alt="Screenshot 2024-05-15 at 1 47 42 AM" src="https://github.com/CryptoMorin/XSeries/assets/48872538/cbce3d98-2120-4478-8bb0-b52a2ba2bd5a">

#### 1.12.2 (Offline Mode)
Only textures applied via a cached UUID will be visible and stacked. None applied with a name are visible, but this is because `SkullUtils.applySkinFromName` skips these cases. They apply correctly otherwise

![Offline 1 12](https://github.com/CryptoMorin/XSeries/assets/48872538/e2ab7b75-ba84-475f-99df-828c28546171)

#### 1.19.4 (Online Mode)
Textures from offline users will be applied on the next tick, causing them not to stack when placed in an inventory. As in 1.12, users with a non-cached UUID are not visible

![Online 1 19](https://github.com/CryptoMorin/XSeries/assets/48872538/c799b76f-aa5a-4ddc-998c-8251b9269717)

<img width="915" alt="Screenshot 2024-05-15 at 2 22 42 AM" src="https://github.com/CryptoMorin/XSeries/assets/48872538/bcac5de2-f4e9-4122-ab3a-a1e64c141bda">

<img width="1162" alt="Screenshot 2024-05-15 at 2 22 33 AM" src="https://github.com/CryptoMorin/XSeries/assets/48872538/1e003a4d-e907-491e-be6e-c72b9502f075">

#### 1.19.4 (Offline Mode)
Textures applied with usernames are visible if the `SkullUtils.applySkinFromName`'s UUID check is ignored, except when the user is logged in. If applied via UUID, the texture will be visible, but only if the server caches it and the user is offline

![Offline 1 19](https://github.com/CryptoMorin/XSeries/assets/48872538/d4eff288-dca5-410b-977f-d8edf80484e8)

#### 1.20.4 (Online Mode)
It works the same as in 1.19. The difference is that this throws an error if the UUID is not cached, since here it returns null for the offline player instance

![Online 1 20](https://github.com/CryptoMorin/XSeries/assets/48872538/4e6b1d78-4e59-464c-985f-5e9827366377)

#### 1.20.4 (Offline Mode)
No textures are applied when using usernames, regardless of disabling `SkullUtils.applySkinFromName` checking for offline uuids

![Offline 1 20](https://github.com/CryptoMorin/XSeries/assets/48872538/30afafc8-0b7f-4d6f-92a7-0bec5cf5fa71)

At first, I had in mind grabbing the server cache, as mentioned in #235, and then requesting an external API. However, this still maintains inconsistencies between versions and online/offline modes

### _Draft for how it could be handled_ (https://github.com/CryptoMorin/XSeries/commit/b69f315aa69ad57fbedb09702902fe748755b441)
It caches all textures but doesn't make those first requests asynchronous, blocking the main thread

#### 1.12.2 (Offline Mode)
![Mod Offline 1 12](https://github.com/CryptoMorin/XSeries/assets/48872538/ba52181a-2c13-4a94-9581-4b614d0ba706)

#### 1.20.4 (Online Mode)
![Mod Online 1 20](https://github.com/CryptoMorin/XSeries/assets/48872538/7d6c4a22-b929-414e-b236-a738c7c6d42c)

**Comment by CryptoMorin** [comment]
Thank you for the detailed report. I briefly reviewed this. I'm just going to sum up the issues with the proposed solution:

* The code will block the main thread for uncached values. This seems to be the case with the server's cache too in older versions. But it's kind of async in newer ones.
* The current code will not properly cache values in case of a temporary network issue (like timeouts) which can be fixed by either requesting again or not caching it and waiting for the next request.
* Even if all the above were fixed, this will double the server's memory, CPU and network usage when the same textures are requested from another plugin since we're keeping our own separate cache. I guess this can probably be fixed with some reflection hackery, but I don't think it's worth it.

Anyways, I've pushed some changes in https://github.com/CryptoMorin/XSeries/commit/421a61a85824056dbca2fcf2cbea59c85f84a6a7 based on your proposed solution. I also made it compatible with offline mode servers.

**Comment by Condordito** [comment]
I made a PR to address those issues, but I'm unsure if XSeries should cache profiles when using base64 textures

- Other plugins may apply additional logic before caching, making XSeries caching redundant
- Recreating those profiles will not affect network usage or significantly consume CPU resources

Although less likely, I think it's not worth doubling memory usage when multiple plugins request the same texture
