### ISSUE TITLE
[XSeries] - Library can no longer be used with v.10.0.0

### ISSUE THREAD

**Issue by timderspieler** [CryptoMorin/XSeries#255]
**Description**
Currently I am trying to switch from XSeries v.9.x.x to v.10.0.0. While the library could be indexed and compiled just fine in the last version, this is no longer the case for v.10.0.0. When switching to this version, my code can no longer be compiled and the library can no longer be indexed.

Switching back to the older version solves the issue.

I have already tried clearing all my caches and updating all used libraries - without luck.

I am currently using:

Java 21 (Target compatibility 8)
Gradle 8.7
Shadow 8.1.1

This is my build.gradle:

`implementation('com.github.cryptomorin:XSeries:10.0.0') { transitive(false) }`

shadow part:
`relocate 'com.cryptomorin.xseries', 'nl.marido.deluxecombat.shaded.xseries'`

I would really appreciate any help regarding this. Thank you very much.

**Comment by CryptoMorin** [comment]
I really don't know how to help. I'm already using it for two of my projects. [Maven](https://github.com/CryptoMorin/SkillsPro/blob/master/pom.xml) and gradle. It's working fine. The simplest way to test whether it should work or not is to manually download it straight from the [Maven repo](https://repo1.maven.org/maven2/com/github/cryptomorin/XSeries/10.0.0/XSeries-10.0.0.jar), and all of the classes are decompiled just fine wtih luyten-0.5.4.

**Comment by CryptoMorin** [comment]
I just released `v11.0.0-beta` see if it helps (the API is quite different depending on what you're using)

**Comment by timderspieler** [comment]
> I really don't know how to help. I'm already using it for two of my projects. [Maven](https://github.com/CryptoMorin/SkillsPro/blob/master/pom.xml) and gradle. It's working fine. The simplest way to test whether it should work or not is to manually download it straight from the [Maven repo](https://repo1.maven.org/maven2/com/github/cryptomorin/XSeries/10.0.0/XSeries-10.0.0.jar), and all of the classes are decompiled just fine wtih luyten-0.5.4 (and the unofficial 0.8.4).
> 
> Also I deleted my maven cache for xseries since I constantly locally install newer versions to test, it pulled v10.0.0 from the servers and continued to work just fine.

Thank you for the information. Sadly its not working with v.11.0.0-beta too. 
The issue seems to be that the sources for the different class files cannot be found. I've already tried to decompile the XSeries-sources.jar but all the classes are present -> IntelliJ itself can't find them.
![grafik](https://github.com/CryptoMorin/XSeries/assets/19387835/c988d998-2564-4d8a-b3f1-c33b68315ef1)

Whats driving me crazy is that it works perfectly fine with v.9.7.0.

**Comment by timderspieler** [comment]
I was using an old version of IntelliJ IDEA. Updating to the latest version helped.

Still, thank you very much @CryptoMorin for your help. I will close this issue now.

**Comment by CryptoMorin** [comment]
Thank you for letting me know what the issue is!
