### ISSUE TITLE
[XSkulls] - Large amount of Lag

### ISSUE THREAD

**Issue by PeachesMLG** [CryptoMorin/XSeries#266]
**Description**
Im trying to get XSkulls working, where it makes all the API requests async in the background, but whilst it is loading these, it will return a default skull, once this is loaded however, it will then grab the data from cache.

I currently have this code here to try manage that: https://github.com/Iridium-Development/IridiumCore/blob/77d355d4cff0fadaf92479ccf55a22968be99b93/plugin/src/main/java/com/iridium/iridiumcore/utils/ItemStackUtils.java#L67

Where it will apply the ItemStack profile async, however when its finished that, it will add it sync from then onwards.

However, given a large GUI when we are showing a lot of skulls at once (a full GUI of 54 heads) this causes a huge amount of lag and eventually crashes my server

https://mclo.gs/W5WkiV2

**Version**
Paper: 1.20.6
XSeries: 11.0

**Comment by CryptoMorin** [comment]
I'm assuming that you create the GUIs before any player even uses it. Are there duplicate skulls in the GUI you're trying to use?

**Comment by PeachesMLG** [comment]
> I'm assuming that you create the GUIs before any player even uses it. Are there duplicate skulls in the GUI you're trying to use?

No a create the GUI when the player opens it, it then automatically refreshes it every second or so.

And no, there arnt any duplicates either, each skull is unique.

**Comment by PeachesMLG** [comment]
I created a test plugin here to replicate whats going on: https://github.com/PeachesMLG/XSkullsTesting

Send me a message on discord if you struggle compiling it, But its creating a GUI full of heads, that refreshes every second (which opens when you right click) and you can see doing so causes the sever to crash

**Comment by PeachesMLG** [comment]
I tried running this async aswell (See my [async branch](https://github.com/PeachesMLG/XSkullsTesting/tree/async)) and its still incredibly slow (although it doesnt have an impact on tps, cuz its async)

I timed it, and it took 2 minutes and 5 seconds to finish rendering the whole GUI (54 heads).

**Comment by PeachesMLG** [comment]
So I wrote some code to get the skin of a player myself, and then passed the base64 skin into XSkulls and the performance different is a lot better: https://github.com/PeachesMLG/XSkullsTesting/tree/get-skin-custom

**Comment by Condordito** [comment]
I also wrote another test with an increased poll size. Some of the usernames don't have a texture, so it will keep trying to fetch them without being able to cache them. It's also hitting a rate limit since it's making a lot of requests. It will eventually cache them all given enough time

![TEST](https://github.com/CryptoMorin/XSeries/assets/48872538/b67e8496-84de-4306-9d6e-6e48b45b51a3)

**Comment by CryptoMorin** [comment]
I made some changes and fixed the cache. I tested it with https://github.com/PeachesMLG/XSkullsTesting username list and it took approx ~1min, but my internet isn't ideal right now, so not sure if it'll perform better on yours.

As for the rate limit issue, from https://wiki.vg/Mojang_API:
> This is currently set at 600 requests per 10 minutes but this may change

Even if we assume that there are 3 requests sent for every username, it wouldn't be anything near 600 for a full inventory. Unless the server sends a lot of requests on startup which I'm not sure about. It's possible that there's a "burst" rate limit too. Or maybe I just got rate limited for repeated testing between restarts.
We can prevent this with our own rate limiter and also fully rate limit ourselves when we get rate limited by the server. But there are issues, like having to send our own requests instead of using `MinecraftSessionService#fetchProfile` if we want to use the rate limiter.

**Comment by PeachesMLG** [comment]
> I made some changes and fixed the cache. I tested it with https://github.com/PeachesMLG/XSkullsTesting username list and it took approx ~1min, but my internet isn't ideal right now, so not sure if it'll perform better on yours.
> 
> As for the rate limit issue, from https://wiki.vg/Mojang_API:
> 
> > This is currently set at 600 requests per 10 minutes but this may change
> 
> Even if we assume that there are 3 requests sent for every username, it wouldn't be anything near 600 for a full inventory. Unless the server sends a lot of requests on startup which I'm not sure about. It's possible that there's a "burst" rate limit too. Or maybe I just got rate limited for repeated testing between restarts. We can prevent this with our own rate limiter and also fully rate limit ourselves when we get rate limited by the server. But there are issues, like having to send our own requests instead of using `MinecraftSessionService#fetchProfile` if we want to use the rate limiter.

So the current username's arnt valid users, and looking into it it takes about a minute like you said.


However, if I set the usernames to a list of users that are real, this finishes in about 3 seconds.


I pulled XSeries down locally and spammed some timing logs everywhere, and it looks like when the usernames arnt valid,

```java
        long startTime = System.currentTimeMillis();
        @Nullable Object profile = GET_PROFILE_BY_NAME.invoke(USER_CACHE, username);
        debug("GET_PROFILE_BY_NAME, took " + (System.currentTimeMillis() - startTime) + "ms");
```

This line of code here can sometimes take up to 3 seconds to execute

```
[19:28:57] [Profile Lookup Executor #0/INFO]: [XSkull] GET_PROFILE_BY_NAME, took 3615ms
```

**Comment by Condordito** [comment]
> This line of code here can sometimes take up to 3 seconds to execute

This is because internally, `GET_PROFILE_BY_NAME` will also try to get the player's UUID to create and cache their profile. There is a 750 ms delay between each failed request

```java
    public Optional<GameProfile> get(String name) {
        String s1 = name.toLowerCase(Locale.ROOT);
        boolean stateLocked = true;
        try {
            Optional<GameProfile> optional;
            this.stateLock.lock();
            GameProfileInfo usercache_usercacheentry = this.profilesByName.get(s1);
            boolean flag = false;
            if (usercache_usercacheentry != null && new Date().getTime() >= usercache_usercacheentry.expirationDate.getTime()) {
                this.profilesByUUID.remove(usercache_usercacheentry.getProfile().getId());
                this.profilesByName.remove(usercache_usercacheentry.getProfile().getName().toLowerCase(Locale.ROOT));
                flag = true;
                usercache_usercacheentry = null;
            }
            if (usercache_usercacheentry != null) {
                usercache_usercacheentry.setLastAccess(this.getNextOperation());
                optional = Optional.of(usercache_usercacheentry.getProfile());
                stateLocked = false;
                this.stateLock.unlock();
            } else {
                stateLocked = false;
                this.stateLock.unlock();
                try {
                    this.lookupLock.lock();
                    optional = GameProfileCache.lookupGameProfile(this.profileRepository, name);
                }
                finally {
                    this.lookupLock.unlock();
                }
                if (optional.isPresent()) {
                    this.add(optional.get());
                    flag = false;
                }
            }
            if (flag && !SpigotConfig.saveUserCacheOnStopOnly) {
                this.save(true);
            }
            Optional<GameProfile> optional2 = optional;
            return optional2;
        }
        finally {
            if (stateLocked) {
                this.stateLock.unlock();
            }
        }
    }
```

```java
public class YggdrasilGameProfileRepository
implements GameProfileRepository {
    private static final Logger LOGGER = LoggerFactory.getLogger(YggdrasilGameProfileRepository.class);
    private static final int ENTRIES_PER_PAGE = 2;
    private static final int MAX_FAIL_COUNT = 3;
    private static final int DELAY_BETWEEN_PAGES = 100;
    private static final int DELAY_BETWEEN_FAILURES = 750;
    private final MinecraftClient client;
    private final URL searchPageUrl;

    public YggdrasilGameProfileRepository(Proxy proxy, Environment environment) {
        this.client = MinecraftClient.unauthenticated(proxy);
        this.searchPageUrl = HttpAuthenticationService.constantURL(environment.servicesHost() + "/minecraft/profile/lookup/bulk/byname");
    }

    @Override
    public void findProfilesByNames(String[] names, ProfileLookupCallback callback) {
        Set criteria = Arrays.stream(names).filter(name -> !Strings.isNullOrEmpty(name)).collect(Collectors.toSet());
        boolean page = false;
        boolean hasRequested = false;
        for (List request : Iterables.partition(criteria, 2)) {
            boolean failed;
            List<String> normalizedRequest = request.stream().map(YggdrasilGameProfileRepository::normalizeName).toList();
            int failCount = 0;
            do {
                failed = false;
                try {
                    ProfileSearchResultsResponse response = this.client.post(this.searchPageUrl, normalizedRequest, ProfileSearchResultsResponse.class);
                    List<Object> profiles = response != null ? response.profiles() : List.of();
                    failCount = 0;
                    LOGGER.debug("Page {} returned {} results, parsing", (Object)0, (Object)profiles.size());
                    HashSet<String> received = new HashSet<String>(profiles.size());
                    for (GameProfile gameProfile : profiles) {
                        LOGGER.debug("Successfully looked up profile {}", (Object)gameProfile);
                        received.add(YggdrasilGameProfileRepository.normalizeName(gameProfile.getName()));
                        callback.onProfileLookupSucceeded(gameProfile);
                    }
                    for (String string : request) {
                        if (received.contains(YggdrasilGameProfileRepository.normalizeName(string))) continue;
                        LOGGER.debug("Couldn't find profile {}", (Object)string);
                        callback.onProfileLookupFailed(string, new ProfileNotFoundException("Server did not find the requested profile"));
                    }
                    if (!hasRequested) {
                        hasRequested = true;
                        continue;
                    }
                    try {
                        Thread.sleep(100L);
                    }
                    catch (InterruptedException interruptedException) {}
                }
                catch (MinecraftClientException e) {
                    if (++failCount == 3) {
                        for (String name3 : request) {
                            LOGGER.debug("Couldn't find profile {} because of a server error", (Object)name3);
                            callback.onProfileLookupFailed(name3, e.toAuthenticationException());
                        }
                        continue;
                    }
                    try {
                        Thread.sleep(750L);
                    }
                    catch (InterruptedException interruptedException) {
                        // empty catch block
                    }
                    failed = true;
                }
            } while (failed);
        }
    }
```

I think the API should provide a method for making bulk requests. Calling `GameProfileRepository#findProfilesByNames` directly or using the `https://api.minecraftservices.com/minecraft/profile/lookup/bulk/byname` endpoint will be better in this case

**Comment by CryptoMorin** [comment]
> So the current username's arnt valid users, and looking into it it takes about a minute like you said.
> 
> However, if I set the usernames to a list of users that are real, this finishes in about 3 seconds.

Are you saying the entire thing finishes in 3 seconds or the code you wrote below it?


> This is because internally, GET_PROFILE_BY_NAME will also try to get the player's UUID to create and cache their profile. There is a 750 ms delay between each failed request

This is a really weird thing they're doing. It seems like these classes were never meant to be called in the main thread but `CraftSkull#setOwner(String)` is using it.
I guess we could make our own version of Mojang's `public Optional<GameProfile> get(String username)` and cache unknown usernames too with just one request.

> I think the API should provide a method for making bulk requests. Calling GameProfileRepository#findProfilesByNames directly.

I will not be adding a bulk version of `SkullInstruction` because this is only going to be useful for usernames and needs a lot of work. We shouldn't be using usernames anyway, UUID is preferred. But we could make something like `CompletableFuture<Void> prepareUsernames(String... usernames)` and cache them.

**Comment by CryptoMorin** [comment]
Also I'm going to start splitting XSkull like XReflection, it's becoming a hellscape.

**Comment by PeachesMLG** [comment]
> > So the current username's arnt valid users, and looking into it it takes about a minute like you said.
> > However, if I set the usernames to a list of users that are real, this finishes in about 3 seconds.
> 
> Are you saying the entire thing finishes in 3 seconds or the code you wrote below it?

The GUI finishes adding items after 3 seconds. So it takes 3 seconds to query 54 heads, which id say is an acceptable amount of time. (When usernames are valid)


Its when the usernames arnt valid that this seems to skyrocket

**Comment by CryptoMorin** [comment]
So with the new code, both the fake list and the real one takes about 12 seconds but it can't finish the real list because I keep getting rate limited.

**Comment by PeachesMLG** [comment]
> So with the new code, both the fake list and the real one takes about 12 seconds but it can't finish the real list because I keep getting rate limited.

Awesome, just pulled latest changes down, and everything seems to be happening in a reasonable amount of time. Appreciate you looking into this.

Ill leave this issue for you to close, but Its all working fine from my side now, thanks :)

**Comment by Condordito** [comment]
https://github.com/CryptoMorin/XSeries/assets/48872538/4602e1a3-cd6b-4501-a897-7f54b36da15a

It fetches all UUIDs and textures almost instantly if it uses the other endpoint, without getting rate limited (tested with a list of 100 valid usernames)

**Comment by CryptoMorin** [comment]
> Demo.mp4
> 
> It could fetch all UUIDs and textures almost instantly if it uses the other endpoint, also without getting rate limited (tested with a list of 100 valid usernames and batches of 10 per request)

I've made a `Profileable.prepare(profiles)`. It doesn't need any major changes and also allows the user to start preparing whenever they want without needing to apply it to an item/block.

The only real issue left is rate limits or temporary network issues. If it ever happens, this method fails.

**Comment by Condordito** [comment]
> The only real issue left is rate limits or temporary network issues. If it ever happens, this method fails

It should handle those exceptions gracefully, returning null and canceling all subsequent requests for a short period of time before re-allowing them. Also, requests made by the server have multiple tries and a delay on failure. Should this be configurable per instruction? (As it now only makes the request once)

**Comment by PeachesMLG** [comment]
> > Demo.mp4
> > It could fetch all UUIDs and textures almost instantly if it uses the other endpoint, also without getting rate limited (tested with a list of 100 valid usernames and batches of 10 per request)
> 
> I've made a `Profileable.prepare(profiles)`. It doesn't need any major changes and also allows the user to start preparing whenever they want without needing to apply it to an item/block.
> 
> The only real issue left is rate limits or temporary network issues. If it ever happens, this method fails. I don't think I'm going to touch that topic for now.

I wanted to clarify, it should fail and then fallback to the "fallback" texture provided in [this commit](https://github.com/CryptoMorin/XSeries/commit/2d7b0a17db7f1abb18c190443176489a0b98d0a6) right? and then will retry  once the internal rate limit (10 minutes) has passed?

Or is that not configured yet and it will just throw an exception?

**Comment by CryptoMorin** [comment]
I added partial support for handling HTTP requests with `ProfileRequestConfiguration` to the prepare() method, but for other requests I'd have to basically pass this object around in most methods to be able to use it. I'll keep it like this until I can figure out if there's a more elegant way to do that.

**Comment by CryptoMorin** [comment]
> > > Demo.mp4
> > > It could fetch all UUIDs and textures almost instantly if it uses the other endpoint, also without getting rate limited (tested with a list of 100 valid usernames and batches of 10 per request)
> > 
> > 
> > I've made a `Profileable.prepare(profiles)`. It doesn't need any major changes and also allows the user to start preparing whenever they want without needing to apply it to an item/block.
> > The only real issue left is rate limits or temporary network issues. If it ever happens, this method fails. I don't think I'm going to touch that topic for now.
> 
> I wanted to clarify, it should fail and then fallback to the "fallback" texture provided in [this commit](https://github.com/CryptoMorin/XSeries/commit/2d7b0a17db7f1abb18c190443176489a0b98d0a6) right? and then will retry once the internal rate limit (10 minutes) has passed?
> 
> Or is that not configured yet and it will just throw an exception?

I'm not sure what you're asking exactly. Of course it will fallback when it fails, but there's nothing to "retry" if the fallback succeed. It will not "retry" anything even if none of the provided fallbacks succeeded. due to any errors like rate limits, server being unavailable, invalid data, etc.
