### ISSUE TITLE
[XSkull] - Base64 support on 1.20.6

### ISSUE THREAD

**Issue by CJCrafter** [CryptoMorin/XSeries#268]
**Description**
I'm trying to use the following code to set a SkullMeta:
```java
   String id = "970e0a59-b95d-45a9-9039-b43ac4fbfc7c";
   String url = "https://textures.minecraft.net/texture/a0564817fcc8dd51bc1957c0b7ea142db687dd6f1caafd35bb4dcfee592421c"
   XSkull.of(itemMeta).profile(XSkull.SkullInputType.UUID, id).apply();
   XSkull.of(itemMeta).profile(XSkull.SkullInputType.TEXTURE_URL, url).apply();
   
   // itemMeta is then set to the ItemStack later in the code...
```

Unfortunately, on 1.20.6 this shows as a Steve head. I've asked around, and it my dev buddies seem to have similar issues with skulls being broken on 1.20.6

**Version**
Paper 1.20.6

**Comment by CryptoMorin** [comment]
I can't find any player with UUID `970e0a59-b95d-45a9-9039-b43ac4fbfc7c`, is this a cracked server? If yes, did this player ever even join the server before?
As for the second one, it's working just fine for me, maybe it's something I did that fixed it, so try the latest commit.

**Comment by Condordito** [comment]
@CryptoMorin 

I've just tested this and it is indeed returning the Steve/Alex texture, but only on the first request. This issue is not specific to version 1.20.6

https://github.com/CryptoMorin/XSeries/assets/48872538/a411d640-350d-45a7-9bf9-ca231c7a77f2

**Comment by CJCrafter** [comment]
> I can't find any player with UUID `970e0a59-b95d-45a9-9039-b43ac4fbfc7c`, is this a cracked server? If yes, did this player ever even join the server before? As for the second one, it's working just fine for me, maybe it's something I did that fixed it, so try the latest commit.

When I got the texture, they provided a UUID and link... I was under the impression that both were needed. From testing, just that link is needed, and the UUID was just some valid UUID. My issue is resolved...

@Condordito, I am going to close this issue since my issue is resolved. It sounds like you are having a separate issue... You should create a new one.
