### ISSUE TITLE
XMaterial - Skull Skin doesn't set when using XMaterial but works fine with Material

### ISSUE THREAD

**Issue by TheSilentPro** [CryptoMorin/XSeries#27]
**Description**
XMaterial - Player Skulls don't show skin. If i use Material# it works fine.
`            ItemStack head = new ItemStack(XMaterial.PLAYER_HEAD.parseMaterial());
            SkullMeta meta = (SkullMeta) head.getItemMeta();
            meta.setOwningPlayer(Bukkit.getOfflinePlayer(online.getUniqueId()));`
*Yes im setting the meta to the itemstack and it works fine when i use Material.PLAYER_HEAD*

**Version**
1.15.2

You must be using the latest version of that utility.
Your server must be using the latest version of that major update.
E.g. 1.14, 1.14.1, 1.14.2 and 1.14.3 are not supported, only 1.14.4 is supported.

**Comment by CryptoMorin** [comment]
You're supposed to use parseItem not parseMaterial.

**Comment by TheSilentPro** [comment]
> You're supposed to use parseItem not parseMaterial.

Changed to `ItemStack head = XMaterial.PLAYER_HEAD.parseItem();` still the same

**Comment by CryptoMorin** [comment]
It's working just fine. I use this a lot myself for skulls. If you debug the item, it's giving you PLAYER_HEAD so it's basically the same if you use Material.PLAYER_HEAD
