### ISSUE TITLE
Spigot is changing the Materials again

### ISSUE THREAD

**Issue by PeachesMLG** [CryptoMorin/XSeries#272]
Looks like spigot are changing a lot of stuff again
![image](https://github.com/CryptoMorin/XSeries/assets/26843204/22a9ae9b-7310-47b7-afb0-c32906847508)

I wasnt able to get too much information, but it looks like all the Enums are going to be deprecated and we will have a new system based on Interfaces instead.

Do we have a plan on how to support these going forwards? Potentially also realted to https://github.com/CryptoMorin/XSeries/issues/239

Discord Link:
https://discord.com/channels/690411863766466590/741875863271899136/1252586934791045160

(Appologies for the lack of information, im not 100% sure as to what the future plans are myself, but ill try update this when I get more info)

**Comment by CryptoMorin** [comment]
I'm already aware of the registries, but I don't think they'll "deprecate" the entire Material class in a sense of `@Deprecated` annotation. Material class will mostly be used for compile-time uses but registries should be used for runtime (config-valued) uses. That's my guess. Whatever happens, XMaterial enum will remain, but like you mentioned, it is related to the other issue, I created this long ago as a prototype: https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/abstractions/Material.java

Also you shouldn't be opening issues for these things, this is more like a casual conversion that should be somewhere else like the main Spigot thread.
