### ISSUE TITLE
[XSkull] - Legacy support

### ISSUE THREAD

**Issue by Condordito** [CryptoMorin/XSeries#273]
**Description**
`ProfilesCore` will try to get `GameProfileCache#getNextOperation`, but this method/field is not present in older server versions. I don't think `MojangAPI#profileFromUsername0` should re-implement the whole method, as the server will already save and check for expired entries every time a user logs in (`PlayerList#placeNewPlayer`)

<img width="1486" alt="Screenshot 2024-06-20 at 7 58 10 AM" src="https://github.com/CryptoMorin/XSeries/assets/48872538/c3e7ff17-e2a4-4292-ba09-ecae0b8af9e4">

**Version**
Spigot 1.8.9, 1.12.2

**Comment by CryptoMorin** [comment]
The `GameProfileCache#getNextOperation` was meant to be null if it wasn't present, I forgot to do that, but sure I guess we can skip the caching mechanism since they're stored for 6hrs anyways.
