### ISSUE TITLE
[XSkull] - Cannot be compiled if using spigot api

### ISSUE THREAD

**Issue by mdaffa48** [CryptoMorin/XSeries#276]
**Description**
When I tried to compile my plugin using `spigot-api`, it says `cannot access com.mojang.authlib.GameProfile` and that error came from the XSkull class and I figured that it's because the `spigot-api` artifact doesn't have `GameProfile.class` included and when I tried to use `spigot` artifact it works without any errors.

This is what I mean by `spigot-api` and `spigot` artifact:
```xml
<dependency>
  <groupId>org.spigotmc</groupId>
  <artifactId>spigot-api</artifactId> // You can use 'spigot' or 'spigot-api' whether to include NMS or not.
  <version>1.21-R0.1-SNAPSHOT</version>
  <scope>provided</scope>
</dependency>
```

To replicate this issue, use the XSkull class specifically applying skull to an `ItemStack.class` with `OfflinePlayer.class` as the profile while using `spigot-api` and you will receive the errors.

These are bunch of filters for XSeries that I used
```xml
<filter>
  <artifact>*:*</artifact>
  <excludes>
    <exclude>com/cryptomorin/xseries/XBiome*</exclude>
    <exclude>com/cryptomorin/xseries/NMSExtras*</exclude>
    <exclude>com/cryptomorin/xseries/NoteBlockMusic*</exclude>
    <exclude>com/cryptomorin/xseries/XBlock*</exclude>
    <exclude>com/cryptomorin/xseries/XEnchantment*</exclude>
    <exclude>com/cryptomorin/xseries/XEntity*</exclude>
    <exclude>com/cryptomorin/xseries/XItemStack*</exclude>
    <exclude>com/cryptomorin/xseries/XPotion*</exclude>
    <exclude>com/cryptomorin/xseries/XSound*</exclude>
    <exclude>com/cryptomorin/xseries/XTag*</exclude>
    <exclude>com/cryptomorin/xseries/messages/ActionBar*</exclude>
    <exclude>com/cryptomorin/xseries/messages/Titles*</exclude>
  </excludes>
</filter>
```

**Version**
1.21 Spigot API
XSeries v11.1.0, Maven Shade Plugin v3.6.0, Maven Compiler Plugin v3.13.0

**Comment by CryptoMorin** [comment]
Unfortunately due to how Maven works, a `provided` transitive dependency will be omitted entirely. You'd have to specify if directly if you want to use spigot-api:

```xml
<repository>
    <id>minecraft-libraries</id>
    <name>Minecraft Libraries</name>
    <url>https://libraries.minecraft.net/</url>
</repository>
<dependency>
    <groupId>com.mojang</groupId>
    <artifactId>authlib</artifactId>
    <version>6.0.54</version>
    <scope>provided</scope>
</dependency>
```

**Comment by stijnb1234** [comment]
Maybe good to mention this somewhere (in the README or wiki?)? I had the same problem.

**Comment by CryptoMorin** [comment]
> Maybe good to mention this somewhere (in the README or wiki?)? I had the same problem.

it's there 
![image](https://github.com/user-attachments/assets/7685d8a0-86c5-47ea-ba58-f9f022ab6afa)
