### ISSUE TITLE
[XMaterial] - Glass Pane always white

### ISSUE THREAD

**Issue by TheSilentPro** [CryptoMorin/XSeries#28]
**Description**
It always returns white stained glass pane
tried #parseItem() too, doesn't work either
If i change it to `Material` it works fine
Method: https://hastebin.com/onutogecol.cpp
No console stacktraces.

**Version**
Paper 1.15

**Comment by CryptoMorin** [comment]
Try this https://pastebin.com/a4Q2n8vG this one works.

**Comment by TheSilentPro** [comment]
> Try this https://pastebin.com/a4Q2n8vG this one works.

Samo issue

**Comment by CryptoMorin** [comment]
![asdfasd](https://user-images.githubusercontent.com/25098093/84735778-d5c91580-af93-11ea-8086-ed0753db5293.PNG)

That was tested in a 1.15 server. Make sure to use the latest 1.15.2 just in case.

**Comment by TheSilentPro** [comment]
It was tested on latest paper build

**Comment by stijnb1234** [comment]
api-version on 1.13 or higher (in your plugin.yml)?
