### ISSUE TITLE
[XReflection] - CraftBukkit version detection using package broken

### ISSUE THREAD

**Issue by stijnb1234** [CryptoMorin/XSeries#280]
**Description**
The version relocation of CraftBukkit has been removed as of 1.20.5, so now CraftBukkit classes are in the main `org.bukkit.craftbukkit` package, without the `.v`.

This affects (and breaks) at least: https://github.com/CryptoMorin/XSeries/blob/7cfcc05b283f97a53063c267504f5f5a46484208/src/main/java/com/cryptomorin/xseries/reflection/XReflection.java#L99-L128

See: https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Version**
1.20.5 or higher

**Comment by CJCrafter** [comment]
This is only in paper, and can be solved using their remapping library... "xyz.jpenilla:reflection-remapper:0.1.1"

**Comment by CryptoMorin** [comment]
findNMSVersionString() is an internal method, just like marked. It's not intended to retain its functionality in newer versions.
