### ISSUE TITLE
[XSkull] Poor Skull Lookup Performance (Profileable of UUID)

### ISSUE THREAD

**Issue by R00tB33rMan** [CryptoMorin/XSeries#284]
**Description**
Newer iterations of the XSeries incur poor performance with skull lookups. Visit the `plugins` tab in this spark report for evidence: https://spark.lucko.me/W807VmiIzF

**Version**
1.20.4 [spark report provides all useful information]

**Comment by CryptoMorin** [comment]
That's because it now properly handles skulls unlike versions before v10.0.0
You should use the applyAsync() to properly handle these cases to avoid lagging the server.
