### ISSUE TITLE
XReflection - NMS_VERSION is returning null on 1.20.6 and newer

### ISSUE THREAD

**Issue by Tigerpanzer02** [CryptoMorin/XSeries#285]
On mc version 1.20.6 and later the return of getVersionInformation will return NMS: null  (NMS_VERSION = null)

It happens because the package isn't returning the numbers anymore

e.g. full line looks like (NMS: null | Parsed: 1.21.0 | Minecraft: 1.21-61-ffe31a1 (MC: 1.21) | Bukkit: 1.21-R0.1-SNAPSHOT)

**Comment by datatags** [comment]
Duplicate of #280 (?)

**Comment by Tigerpanzer02** [comment]
oversaw it sorry
