### ISSUE TITLE
[XEntity] - Cat.Type is no longer an Enum in latest 1.21 builds

### ISSUE THREAD

**Issue by HSGamer** [CryptoMorin/XSeries#287]
**Description**
Look like Spigot changed the type of Cat.Type from Enum to Interface, and required us to get it from `Registry`

From the build log: https://jitpack.io/com/github/CryptoMorin/XSeries/5788570d9d/build.log
From the deprecation notice: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Cat.Type.html#valueOf(java.lang.String)

**Version**
1.21

**Comment by xGinko** [comment]
Same for frog variants, map cursor types, and villager types+profession.
