### ISSUE TITLE
[ParticleDisplay] - Count cannot be set to 0 is a problem

### ISSUE THREAD

**Issue by SuperMax8** [CryptoMorin/XSeries#288]
**Description**
In the class ParticleDisplay line 925
if (this.count == 0) {
                this.count = 1;
            }

you force count to not be 0
With some particles we need to use a count at 0, for campfire_cosy_smoke particle for example, setting it to 0 change the behavior of the particle compared to like 1

for campfire_cosy_smoke:
with count at 1 the particle doesn't follow the direction
with count at 0 the particle follow the offsets direction

so we need the possibility to set it to 0

**Comment by datatags** [comment]
That shouldn't be an issue as of PR #265, which was released in XSeries v11.1.0. If you set a direction for the particle, it will internally pass a count of 0 to Bukkit's `spawnParticle` method, but will spawn the number of particles you ask for in `withCount()` using a loop. See [here](https://github.com/CryptoMorin/XSeries/blob/f769d0d22f328100ecfaaedec2d1c56cf71af695/src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java#L1607) for how that logic works

**Comment by SuperMax8** [comment]
Oh ok that's the thing I missed, I needed to use the .particleDirection() and not .offset()
thanks for your response
