### ISSUE TITLE
[XSkull] - Split up reflection

### ISSUE THREAD

**Issue by AlexProgrammerDE** [CryptoMorin/XSeries#290]
**Description**
Please only load reflection code when necessary using separate classes. I don't want it when mc reflection in ProfilesCore breaks due to Session server classes changing. Like for example recently the proxy thing was broken. I only use the "set skull from texture hash" feature. I don't need any of the code that resolves what proxy the mc server uses. So please only load the "retrieve profile skin from sessionserver" reflection code only when a profile is being set using a type that needs web requests/deeper access into the server.

The "proxy reflection" issue from the last release broke my plugin even though I only use texture hash.

**Comment by CryptoMorin** [comment]
Maybe you could also post the error so we could fix that too?

**Comment by AlexProgrammerDE** [comment]
The error was fixed by 11.2.0.1. But my point still stands about reflection.
