### ISSUE TITLE
[XPotion] - Missing TURTLE_MASTER potion

### ISSUE THREAD

**Issue by Wekylend** [CryptoMorin/XSeries#294]
**Description**
Hello! First off thank you for providing us with this super helpful library. :)

The XPotion enum doesn't have the [TURTLE_MASTER](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html#TURTLE_MASTER) potion. Not sure if it's a wanted behavior or was just overlooked. Thanks in advance. :)

**Version**
Introduced in version 1.13

**Comment by Wekylend** [comment]
Hello, thanks for getting back to me!

Correct it's quite awkward but seems doable to make it work with XPotion enum.
The Bukkit `PotionType` enum does have a `TURTLE_MASTER` value referencing only the `PotionEffectType.SLOW` at the moment (which isn't that big of a deal). Ideally It would be good to have something like this?

```java
// Have this method return XPotion.TURTLE_MASTER via "TURTLE_MASTER"
public static Optional<XPotion> matchXPotion(@Nonnull String potion);

// Have this method return XPotion.TURTLE_MASTER via PotionType.TURTLE_MASTER
public static XPotion matchXPotion(@Nonnull PotionType type);

// Unreachable for XPotion.TURTLE_MASTER as PotionEffectType.SLOWNESS will be XPotion.SLOWNESS
// and PotionEffectType.DAMAGE_RESISTANCE will be XPotion.RESISTANCE
public static XPotion matchXPotion(@Nonnull PotionEffectType type);
```

Let me know your thoughts. This use-case has popped up working on one of my projects, and it uses the String to PotionType mapping via XPotion and basically makes the PotionType.TURTLE_MASTER. (Special case indeed 😄)

**Comment by CryptoMorin** [comment]
Sure and I guess we can make https://github.com/CryptoMorin/XSeries/blob/b11b176deca55da6d465e67a3d4be548c3ef06c6/src/main/java/com/cryptomorin/xseries/XPotion.java#L437-L440 return SLOWNESS like bukkit.
