### ISSUE TITLE
[XSeries] Attempt match on native server Enum for forward compatibility?

### ISSUE THREAD

**Issue by cervinakuy** [CryptoMorin/XSeries#296]
**Description**
This isn't necessarily a bug, but rather a potential logic change request.

For most (if not all) matchX(...) methods, would it be possible to first add a simple native check prior to doing any advanced matching logic? This would be incredibly beneficial, as in theory, it should allow for some degree of automatic forward compatibility.

Take XMaterial for example, the native check logic could look like so:
```
Material possibleNativeMaterial;
try {
    possibleNativeMaterial = Material.valueOf(materialValue);
} catch (IllegalArgumentException exception) {
    possibleNativeMaterial = null;
}

if (possibleNativeMaterial != null) {
    // native material found; use accordingly
} else {
    // no native material found; do existing advanced XMaterial logic
}
```
(or I suppose you could flip the order too if preferred: if XMaterial logic fails to find a match, prior to returning null, do a native check)

Since my freetime is incredibly limited, I have added this logic to my [KitPvP kit item parser](https://github.com/cervinakuy/KitPvP/blob/47e369a4dca8e8d5cdf1a43933ae6039a0b563e3/src/main/java/com/planetgallium/kitpvp/item/AttributeParser.java#L74-L101), so that even when I have yet to update KitPvP to the latest server version in the future, users can still use new items in their kits. But I would imagine other developers would also benefit from this behavior, and especially across all XSeries utilities. In my case, I have only added this logic when using XMaterial since items are fundamental in my plugin, but I would also need to add this logic when handling enchantments, potion effects, etc.

Let me know if this is clear and if any clarifications are necessary; XSeries has been a critical part of KitPvP over the years :)

**Comment by CryptoMorin** [comment]
The problem is that the matchX...() methods that you mention must return an `XMaterial` So I can't really use the `possibleNativeMaterial` even if it's found. I can't magically add new entries to the class because it's an enum (well it's technically possible with bytecode manipulation but that's out of scope)

This is one of the issues that https://github.com/CryptoMorin/XSeries/issues/239 solutions can fix.

**Comment by cervinakuy** [comment]
Ah, understood. Perhaps a good experimental middle ground would be to incrementally implement static members in the smaller XSeries utilities one by one. And over time, if everything functions well, eventually all XSeries utilities could use static members; as I do understand it would be a significant undertaking if done simultaneously.

Regardless, I think forward compatibility for XSeries would be huge, enabling mostly automatic support for newer server versions even when XSeries hasn't been updated yet. This would also apply to abandoned plugins that use XSeries, allowing them to continue functioning long-term.

I'll close this issue, but I really believe static members is the way to go. If you haven't already, I would also recommend chatting with ChatGPT on this topic as a thought partner, maybe there's another easier solution too you haven't considered ;)
