### ISSUE TITLE
[XSkull] - New "public ResolvableProfile profile" field of CraftMetaSkull causes reflection issues on v1.21.1b78+

### ISSUE THREAD

**Issue by datatags** [CryptoMorin/XSeries#298]
**Description**
XSkull has once again encountered a reflection error, occurring on the most recent server builds for 1.21.1. Stack trace: https://pastebin.com/xUdChkPb

**Version**
XSeries 11.2.0
Happens on Spigot (`CraftBukkit version 4316-Spigot-a759b62-8a6f8b6 (MC: 1.21.1)`) and Paper (`Paper version 1.21.1-81-master@13a2395 (2024-09-15T20:39:09Z)`)

**Comment by dlsf** [comment]
Can confirm that this is an issue
