### ISSUE TITLE
ActionBar - Issue

### ISSUE THREAD

**Issue by EazyFTW** [CryptoMorin/XSeries#30]
**Description**
The actionbar function does not work:
https://i.eazyftw.com/tjd1RcN.java

**Version**
1.16.1

**Comment by CryptoMorin** [comment]
Make sure you have api-version set to 1.13 in your plugin.yml

**Comment by EazyFTW** [comment]
That wouldn't have anything to do with it, and it does.

**Comment by EazyFTW** [comment]
This was an issue with it not updating or something. Has been fixed some how. #31 is still an issue though.
