### ISSUE TITLE
[XMaterial] - NoClassDefFoundError

### ISSUE THREAD

**Issue by mehboss** [CryptoMorin/XSeries#302]
**Description**
Latest utility version. I just started using maven eclipse with my plugin and this is probably my mistake, but I am encountering an error, which I have attached below.

I perform Maven->Update Project and then Run as -> Maven Install

Line 335:
Optional<XMaterial> type = XMaterial.matchXMaterial(getConfig().getString(item + ".Item").toUpperCase());`

Error: https://pastebin.com/ZWPgP5B4
Pom: https://pastebin.com/XSDTCnNF

**Version**
This server is running Paper version git-Paper-336 (MC: 1.20.4)

I appreciate any assistance. It works fine just on its own class, but when shaded in using maven I get this error. Again, this is the first time I've used maven, so I may be compiling it wrong or something..

**Comment by CryptoMorin** [comment]
I'm not sure how you consider this shading, but did you read the guide on the [main page](https://github.com/CryptoMorin/XSeries/?tab=readme-ov-file#shading)?

**Comment by mehboss** [comment]
I did read the guide, but apparently I am blind and missed this part. Thank you
