### ISSUE TITLE
[XItemStack] - giveOrDrop NoSuchMethodError on 1.8.8

### ISSUE THREAD

**Issue by tomwmth** [CryptoMorin/XSeries#303]
**Description**
```java
    @Execute
    public void execute(@Context CommandSender sender, @Arg("player") Player player) {
        ItemStack item = new ItemBuilder()
                // ...
                .build();
        XItemStack.giveOrDrop(player, item);
    }
```

https://pastebin.com/S4Vt1gJm

**Version**
Latest XSeries (11.3.0)

Java 8

Unmodified Paper for 1.8.8 (build 445) obtained from their build explorer
`/ver` returns "CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)"

**Comment by CryptoMorin** [comment]
I'm just going to leave the stacktrace here, because it's more accessible this way:

```hs
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
 	at com.cryptomorin.xseries.XItemStack.addItems(XItemStack.java:1284)
```
