### ISSUE TITLE
[MinecraftConnection] - NoSuchFieldException

### ISSUE THREAD

**Issue by aematsubara** [CryptoMorin/XSeries#306]
**Description**
When trying to send a packet with `MinecraftConnection.sendPacket(Player, Object);` the error appears; basically the PLAYER_CONNECTION field was renamed to `f` (OBFUSCATED) in 1.21.2.

Using: com.github.cryptomorin:XSeries:11.3.0

Error: https://pastebin.com/RJKp8zZU

Adding v(21, 2, “f”) to the mappings of PLAYER_CONNECTION fixes the error (I don't have time to make a pull request, otherwise I would do it).
```
private static final MethodHandle PLAYER_CONNECTION = ServerPlayer
            .field().getter()
            .returns(ServerGamePacketListenerImpl)
            .map(MinecraftMapping.MOJANG, "connection")
            .map(MinecraftMapping.OBFUSCATED, v(21, 2, "f").v(20, "c").v(17, "b").orElse("playerConnection"))
            .unreflect();
```

**Version**
Spigot 1.21.3

**Comment by CJCrafter** [comment]
Probably worth grabbing the player connection object by type rather than by field name... Will be much more stable across versions.

**Comment by CryptoMorin** [comment]
I'm planning to make a lenient version of XReflection to handle definitions based on certain patterns instead of providing the full definition, but we have to keep using the current approach for now.

**Comment by CJCrafter** [comment]
If I may...

https://github.com/CJCrafter/FoliaScheduler/blob/master/src/main/java/com/cjcrafter/foliascheduler/util/ReflectionUtil.java
