### ISSUE TITLE
Titles - Issue

### ISSUE THREAD

**Issue by EazyFTW** [CryptoMorin/XSeries#31]
**Description**
Clearing a title isn't working due to 1.16.1 most likely:
https://i.eazyftw.com/KxMvE3H.java

**Version**
1.16.1

**Comment by CryptoMorin** [comment]
You're using your own version.
**com.eazyftw.ezcolors.versions.messages.Titles.clearTitle(Titles.java:254)**

**Comment by EazyFTW** [comment]
It's the same file as Titles.

https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/messages/Titles.java

**Comment by CryptoMorin** [comment]
It's obviously not the same file, where did you get the number "233" from the error you posted? Whether you added or removed things, it's still not the same file. I don't want to just guess the line.

Anyways, I found the solution.
The clear method ignores if Bukkit can handle this or not.
For now you can fix it on your side with a simple check in the clear method:
`if (SUPPORTS) {
   player.resetTitle();
   return;
`

**Comment by EazyFTW** [comment]
I copied the file and the legal stuff was in it 2 times accidentally, but it's the same file. For now, I just made it send a blank title for 1 stick instead.
