### ISSUE TITLE
[XMaterial] - 1.21.4 Support

### ISSUE THREAD

**Issue by ImYenil** [CryptoMorin/XSeries#317]
1.21.4 Support

**Comment by kangarko** [comment]
Yeah some names like RESIN_CLUMP are missing. I already fixed it in our fork in case you want it sooner: https://github.com/kangarko/Foundation/commit/c4188707a03283f13966a8121db487bb63f56e04

**Comment by CryptoMorin** [comment]
You could also make a PR too.

**Comment by kangarko** [comment]
@CryptoMorin Sure! https://github.com/CryptoMorin/XSeries/pull/318
