### ISSUE TITLE
[XItemStack] - serialize() as default

### ISSUE THREAD

**Issue by stijnb1234** [CryptoMorin/XSeries#36]
**Description**
It would be great if you could serialize() a default itemstack. 

It doesn't put it in a ConfigurationSection, but you just specify the path, and then it saves it with addDefault().

**Comment by CryptoMorin** [comment]
Can you explain a little more? If you have the path, then you can get the ConfigurationSection for that path. What's the difference?

**Comment by stijnb1234** [comment]
But how do you create an instance of the ConfigurationSection for a default?

**Comment by CryptoMorin** [comment]
FileConfiguration#getDefaults().getConfigurationSection(...) ?

**Comment by stijnb1234** [comment]
Okay, and does that work with a reference? So that I can use it like this: Or?

```java
ConfigurationSection sec = FileManager.getInstance().getConfig().getDefaults().getConfigurationSection("Shop.test.Items.1.Item");
XItemStack.serialize(defaultStack, sec);
```

**Comment by CryptoMorin** [comment]
Wait why would you want to serialize something into the default config? Just serialize it directly to the config.

**Comment by robertlit** [comment]
> Okay, and does that work with a reference? So that I can use it like this: Or?
> 
> ```java
> ConfigurationSection sec = FileManager.getInstance().getConfig().getDefaults().getConfigurationSection("Shop.test.Items.1.Item");
> XItemStack.serialize(defaultStack, sec);
> ```

The ```ConfigurarionSection``` will be ```null``` if it doesn't exist, what you probably want is ```createSection(path)```

**Comment by stijnb1234** [comment]
Thanks. Will try that.

> Wait why would you want to serialize something into the default config? Just serialize it directly to the config.
Because it's a default value, I want everyone to be able to remove the default without him coming back every time.

**Comment by CryptoMorin** [comment]
I think this is solved. I'm closing this.
