### ISSUE TITLE
Javax annotations in XMaterial

### ISSUE THREAD

**Issue by NoChanceSD** [CryptoMorin/XSeries#4]
First of all, thank you for your work, made my life a lot easier.
About this issue, maybe i'm missing some dependency but it seems to me that these annotations are only present if you have the full Spigot/Craftbukkit as a dependency.

So if i'm only using the spigot-api i can't import them, as an example i had to remove them here: https://github.com/NoChanceSD/AncientGates/blob/master/src/main/java/org/mcteam/ancientgates/util/XMaterial.java to get it to compile.

**Comment by CryptoMorin** [comment]
Oh, right I forgot about that.
The nullability annotations aren't necessary it's just for the docs, so you can remove them without anything breaking.

I was planning to use Checker Framework but that needs another dependency, but you don't need to compile it with your plugin if you're using the null annotations only.
Another thing I can do is to use IntelliJ annotations but some devs are still using Eclipse...

If it's getting complicated for everyone I might just remove them.

**Comment by NoChanceSD** [comment]
One option could be you adding a maven repository and we would just depend on it without needing to copy paste the class, then you could probably use whatever you want as annotation. 
Other options would be changing to something else, maybe guava or apache commons have some null annotations of their own, i'm not sure about that, or just removing them.

**Comment by CryptoMorin** [comment]
Try this:

`<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.2</version>
</dependency>`
https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305

**Comment by NoChanceSD** [comment]
Alright, that works too i guess, thanks.
A bit unrelated but i noticed that XMaterial.WATER.parseMaterial() returns WATER in 1.8 as well, shouldn't it return STATIONARY_WATER on 1.13-? Or should i not use parseMaterial and i'm using it wrongly?

**Comment by CryptoMorin** [comment]
STATIONARY_WATER and WATER are only used for blocks.
In 1.13+ it's changed to [Levelled](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/Levelled.html) water flowing system.
Since it's we're talking about blocks, it's unrelated to XMaterial. I will add it to XBlock instead.

**Comment by NoChanceSD** [comment]
In my case i only need the material though, i'm just comparing a block's gettype and i needed to check if it's Material.STATIONARY_WATER on 1.13- and Material.WATER on 1.13+, which is what i assumed XMaterial.WATER.parseMaterial would return based on the version.

**Comment by CryptoMorin** [comment]
But that's the thing tho, you're still comparing blocks.
If I wanted to add all these exceptions to XMaterial it'd be a huge mess.

Simply there's no way to fix this in XMaterial because it's not even a bug.
The code doesn't know which material you want. Since both material exists it just returns WATER, because that's the material that exists in 1.13 too, so it has a higher priority.

You can do it with a simple method:
`public static boolean isWaterStationary(Block block) {
    return XMaterial.isNewVersion() ? block.getType() == Material.WATER : block.getType().name().equals("STATIONARY_WATER");
}`
But in 1.13 they're both are water. So it just wouldn't work. Unless you're trying to do sth different that I don't know.

`public static boolean isWaterStationary(Block block) {
    return XMaterial.isNewVersion() ? block.getType() == Material.WATER : XBlock.getFluidLevel(block) < 7;
}`
That is the right way if you're trying to check if water is stationary.

**Comment by NoChanceSD** [comment]
I understand but i wrongly assumed it would return the old material name defined in the constructor when run on older versions like 1.8.
I was just trying to find a way to better utilize this library because basically i ended up doing this: https://github.com/NoChanceSD/AncientGates/blob/master/src/main/java/org/mcteam/ancientgates/util/types/GateMaterial.java#L24 for some of the materials and at this point i wouldn't even need the library. Anyway, thank you, the issues i had are now solved.
