### ISSUE TITLE
[XMaterial] - Duplication problems - can't request Melon

### ISSUE THREAD

**Issue by SkytAsul** [CryptoMorin/XSeries#40]
**Description**
On 1.15.2, using `XMaterial.matchXMaterial(Material.MELON)` returns `XMaterial.MELON_SLICE`, while I'd like to get `XMaterial.MELON` (the block material).

**Version**
Spigot 1.15.2.

**Comment by CryptoMorin** [comment]
XMaterial is for ItemStacks. It's prioritizes ItemStack logic, the code can't know what you desire.
You might want to look into [XBlock](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XBlock.java). See if the method you want is there.

**Comment by SkytAsul** [comment]
Unfortunately the method I'm looking for is not present in XBlock :/
To be precise, this is what I want:
> Users can select a XMaterial which will be stored in the field "userMaterial".
> When they break blocks, the plugin will compare the Bukkit Material of the block with the XMaterial "userMaterial" selected before.
> However, if users select `XMaterial.MELON` and break a `Material.MELON` it will not work, because `XMaterial.matchXMaterial(Material.MELON)` will return `XMaterial.MELON_SLICE`. I can't see how to prevent this from happening :/

**Comment by CryptoMorin** [comment]
XBlock.isType is what you're looking for. But I haven't added a melon method to it yet.

**Comment by SkytAsul** [comment]
Okay I'll use this, thank you!

**Comment by CryptoMorin** [comment]
XBlock.isType now supports melons as from 6.0.2
