### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#51]
**Description**
Examples should be removed. Unit tests should be in src/test/java package.

**Comment by CryptoMorin** [comment]
Why would I remove that class? It's not only about tests. It also has other methods too and other random stuff I want to keep for future issues.

**Comment by portlek** [comment]
> Why would I remove that class? It's not only about tests. It also has other methods too and other random stuff I want to keep for future issues.

the example class should be separated into wiki/usage or something like that.

**Comment by CryptoMorin** [comment]
Moved examples.java to the wiki section.
