### ISSUE TITLE
XMaterial - Some items are not shown in lower versions.

### ISSUE THREAD

**Issue by JoelDeadMach** [CryptoMorin/XSeries#56]
**Description**
So currently i am using XMaterial, I need to say you did a great job right there, but I am facing some issues at XMaterial. Some items are not showing correctly. Example item repeater and brewing stand arent showing in lower versions while it does on 1.16 version or higher. I have defined the api-version as you stated and followed the instructions. Either way parseMaterial() and parseItem() gives the same thing. Here on the screen below you see what is going on:

on 1.16.2 it shows all items fine in the GUI as shown here below:
http://i.insanemc.net/javaw_dYiXGOcHbn.png

And on lower (in this screen 1.12.2) it does not show all items.
http://i.insanemc.net/javaw_fh0LGdS7wE.png 

I also found out some other items arent showing on lower versions but these came now to my mind since I needed them. What can I do to fix those issues?

King regards, 
Joel. B.

**Version**
In version 1.16.2 (latest build) works fine.
on lower it does'n show the item.

**Comment by CryptoMorin** [comment]
If you could remember the other items that didn't show, that'd be great. I'll fix those two for now.

**Comment by JoelDeadMach** [comment]
Thank you, i will look for more items that arent showing, thanks already for this fix and will test it out 😄

**Comment by JoelDeadMach** [comment]
Can you let me know when you pushed the fix?

**Comment by JoelDeadMach** [comment]
So about the other items, currently i can not find any others. The main items are currently REPEATER and BREWING_STAND not showing under 1.12

**Comment by CryptoMorin** [comment]
Fixed in v7 (the repo is under maintenance. The new build should be available after a few hours)
