### ISSUE TITLE
[XMaterial] - XMaterial.MAGENTA_BED.parseItem() returns BED with data

### ISSUE THREAD

**Issue by RoinujNosde** [CryptoMorin/XSeries#64]
**Description**
As you can see on the screenshot below, when using XMaterial.MAGENTA_BED.parseItem(), the bed is not displayed correctly.
After some testing I discovered that the item data is causing the problem. If you look at the last message of the debug, the data is 2.
**Just using XMaterial.MAGENTA_BED.parseMaterial() works fine.** Don't know if it's really an issue or is intended.

Testing code:
```java
XMaterial material = XMaterial.MAGENTA_BED;
System.out.println("material = " + material);
System.out.println("material.parseItem(true) = " + material.parseItem(true));
System.out.println("material.parseMaterial(true) = " + material.parseMaterial(true));
System.out.println("material.parseMaterial(false) = " + material.parseMaterial(false));
System.out.println("material.parseItem(false) = " + material.parseItem(false));
System.out.println("material.parseItem(true).getData() = " + material.parseItem(true).getData());
```
The code above outputs:
```
[19:32:38 INFO]: material = Magenta Bed
[19:32:38 INFO]: material.parseItem(true) = ItemStack{BED x 1}
[19:32:38 INFO]: material.parseMaterial(true) = BED
[19:32:38 INFO]: material.parseMaterial(false) = BED
[19:32:38 INFO]: material.parseItem(false) = ItemStack{BED x 1}
[19:32:38 INFO]: material.parseItem(true).getData() = BED(2)
```
Using XMaterial.MAGENTA_BED.parseItem(true):
![image](https://user-images.githubusercontent.com/6441328/91102730-1c945500-e640-11ea-9aea-90e24f1082da.png)

**Version**
 CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by CryptoMorin** [comment]
>  CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Colored beds (other than red) do not exist in 1.8.8 They were added in [1.12](https://minecraft.gamepedia.com/Bed)

**Comment by RoinujNosde** [comment]
Shouldn't it fallback to a regular bed on 1.8?

I'm asking out of curiosity, since parseMaterial has the result I want.

**Comment by CryptoMorin** [comment]
Actually I did thought about doing this before, but considering that this is the only material type with this issue, it's not worth the performance impact (although it's not significant). I might consider changing the version check system in the future.

**Comment by RoinujNosde** [comment]
Got it.
If I later decide to support bed colors on 1.12, I can just make a version check.

Thanks.
