### ISSUE TITLE
[XMaterial] - IllegalArgumentException "RESSURE_PLATE"

### ISSUE THREAD

**Issue by andrew121410** [CryptoMorin/XSeries#65]
**Description**
My plugin uses XMaterial to see if block/material is FARMLAND by using matchMaterial in PlayerInteractEvent but after upgrading to 7.2.1 I get java.lang.IllegalArgumentException: Unsupported material with no data value: RESSURE_PLATE.

**Comment by CryptoMorin** [comment]
Hi, please provide your code and the full error log.

**Comment by andrew121410** [comment]
So this error happens when I step on a pressure plate: https://sourceb.in/691c8bf532
Here's the code:
https://ibb.co/Sy8PSGm
https://ibb.co/xjNqnNy

**Comment by CryptoMorin** [comment]
> java.lang.IllegalArgumentException: Unsupported material with no data value: RESSURE_PLATE
Yes, there is no such [material](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) called **RESSURE_PLATE** indeed. 
I guess this is a typo error in a 1.16.2 version. Try updating your server.

**Comment by andrew121410** [comment]
That's weird because having a debug message that prints out block.getType it looks correct. 
https://ibb.co/Qmy8rwP
https://ibb.co/X7v3kwN

**Comment by CryptoMorin** [comment]
I'm not sure either, your exception is thrown from [here](https://github.com/CryptoMorin/XSeries/blob/8a77f7b24e036b1614876ef7ecb8d68c2122f059/src/main/java/com/cryptomorin/xseries/XMaterial.java#L1558) as you can see the name it outputs is directly using `Material#name()`
