### ISSUE TITLE
[ActionBar] - 1.16.2 Does not accept colors

### ISSUE THREAD

**Issue by TheSilentPro** [CryptoMorin/XSeries#66]
**Description**
ActionBar doesn't display color in 1.16.2
Utility Version:  2.1.1
Code Snips:
https://hastebin.com/igupeguyib.css
https://hastebin.com/dapufadafi.pl

**Version**
![image](https://user-images.githubusercontent.com/46107752/93076025-feda6e80-f686-11ea-83c7-b3cdc5a9507c.png)

**Comment by TheSilentPro** [comment]
Updated paper, still same issue
![image](https://user-images.githubusercontent.com/46107752/93078603-0f8ce380-f68b-11ea-8dc5-8afae754ac9a.png)

**Comment by CryptoMorin** [comment]
Te links you sent are empty. I recommend you to use Pastebin instead as Hastebin randomly deletes pastes.
But I assume you're not colorizing the text that you're passing to the method, this is completely normal, the utility doesn't colorize.

**Comment by TheSilentPro** [comment]
Weird the links are not empty for me. Here's them on pastebin:
https://pastebin.com/MKTLpN3R
https://pastebin.com/x3BxhCBd
And yes i am colorizing them. The & symbols get translated but no color is given to the text.

**Comment by CryptoMorin** [comment]
I'm unable to reproduce this using the Paper version you gave me.
`ActionBar.sendActionBar(Kingdoms.get(), player, ChatColor.RED + "CANCELLED", 20);`
![CANCEL](https://user-images.githubusercontent.com/25098093/93222326-60214100-f75e-11ea-9c5c-5afc6d753e2c.PNG)

**Comment by TheSilentPro** [comment]
Could it be because of protocolsupport? If im on 1.8 it wont show color, but on 1.15.2 it still worked idk why 1.16 would be different

**Comment by CryptoMorin** [comment]
Yes, it's possible that ProtocolSupport or ViaVersion can be the cause since they modify packets.

**Comment by TheSilentPro** [comment]
When on 1.16.3 it shows the colors so yeah its from protocolsupport

**Comment by Butterness01** [comment]
Same happens with ViaBackwards. They say the problem is that the actionbar is being sent using the chat packet instead of the title packet.

**Comment by CryptoMorin** [comment]
`Player#spigot().sendMessage()` also, uses `PacketPlayOutChat` and not `PacketPlayOutTitle`
