### ISSUE TITLE
[XMaterial] - Data not working? 

### ISSUE THREAD

**Issue by KinooDev** [CryptoMorin/XSeries#69]
**Description**
I have a String, like "INK_SACK:8", and when i use XMaterial.matchXMaterial(config.getString("material"); it only loads the ink sack, not the "8" data. Im using that method because i saw that it Checks if is newer version or older... 
**Note:** Issues caused by plugins such ProtocolSupport or ViaVersion should be reported to the plugin developers, not here. 

**Version**
Base coding in 1.12.2, but from 1.8 to 1.16.2 for all compatibility.

**Comment by CryptoMorin** [comment]
Please explain what you mean by `it only loads the ink sack`. How did you exactly debug this?

**Comment by KinooDev** [comment]
Look at this:
`DefaultItemBuilder(String material, int amount) {
        this(KMaterial.getMaterial(material), amount);
    }`

so the KMaterial.getMaterial(material) is this 
`public static Material getMaterial (String material) {
        return XMaterial.matchXMaterial(material).isPresent() ? XMaterial.matchXMaterial(material).get().parseMaterial() : XMaterial.AIR.parseMaterial();
    }`

when i put in that String "INK_SACK:8", it only gives me a inksack (dye with data 1)

**Comment by CryptoMorin** [comment]
That's not how you're supposed to use it. If you only parse the material, it'll only return INK_SACK and ye, that's intended.
You might want to return the ItemStack, which includes the data value.
