### ISSUE TITLE
[XMaterial] - Expose anyMatchLegacy

### ISSUE THREAD

**Issue by pablo67340** [CryptoMorin/XSeries#70]
**Description**
When using XMaterial, one method in the library stands above all when it comes to legacy detection. 

anyMatchLegacy();

This method however is set to private, which prevents me from using XSeries directly from maven due to the fact that I need to set this to public myself. A plugin I maintain called GUIShop heavily relies on this method, to pre-verify if an item mentioned in the config could be legacy or not, well before Itemstack building even begins. 

Setting this method to public would solve all the problems I've been having with XMaterial, all while allowing me to hook XSeries into maven directly.

Thanks, please get back soon!

~Bryce

**Comment by CryptoMorin** [comment]
Like the method docs says, `All the values passed to this method will not be null or empty and are formatted correctly.`
So I'd have to expose format() and check for nulls too.

They're not exposed for a reason. Are you changing your entire ItemStack building system just by looping through all the materials in config and checking if one of them is a legacy material? It's not a good ItemStack builder if it needs that. You should consider changing your system instead. What's exactly different about the ItemStack builder if the item is legacy?

If you insist, you can always copy the method to another class and use. It's only a few lines.

**Comment by pablo67340** [comment]
I don't see why you'd need to expose format at all, I've been able to set it to public, nothing more, and it works fine.

This is an example as to why we use anyMatchLegacy

Rather than comparing for multiple different spawner names, we can do this instead

`XMaterial spawnerXMaterial = XMaterial.SPAWNER;
 return material.equalsIgnoreCase(spawnerXMaterial.name()) || spawnerXMaterial.anyMatchLegacy(material)`

This will check for the standard SPAWNER item, but also look for any other items that could match the requested material sent in by the user. This is so we can apply our NBT and hook into our mob spawner placement events to change the mob type upon placing.

**Comment by CryptoMorin** [comment]
That's the whole point of the utility. Instead of manually comparing multiple legacy names, it automatically handles it for you.
I'm assuming your "material" class variable is a string which you should be saving it as a XMaterial instead.
So by doing that, you simply just do
```java
return material == XMaterial.SPAWNER;
```

Now if for some reasons you don't want to do that, you have to match the material every time you want to check.
```java
Optional<XMaterial> mat = XMaterial.matchXMaterial(material);
return mat.orElse(null) == XMaterial.SPAWNER;
```

**Comment by pablo67340** [comment]
Thanks
