### ISSUE TITLE
[XItemStack] - Add deserialize(Map<String, Object>) and Map<String, Object> serialize(ItemStack) methods.

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#71]
XItemStack class has already `deserialize` and `serialize` methods; however, the ways are taking the Bukkit's configuration section. In this case, developers who don't use the Bukkit configuration library can't use them, so I think the method should support the Map too.

An example;
https://github.com/portlek/BukkitItemBuilder/blob/master/src/main/java/io/github/portlek/bukkititembuilder/util/ItemStackUtil.java

**Comment by CryptoMorin** [comment]
ItemStack serialization is specifically meant to support configuration files only. It's not for datas (well, if you're using another format for configuration files, it just wouldn't make sense)
If I turn it into a Map parser, it'll heavily impact performance.
I personally use **MojangsonParser** which requires reflection to save item datas.

**Comment by portlek** [comment]
I don't think it will impact performance. The original method will be the same. The configuration section will give its map value into the deserialize method. That won't impact performance. But yeah it's your library your choice anyway.
