### ISSUE TITLE
[XEffect] - Add a XEffect class to replace org.bukkit.Effect

### ISSUE THREAD

**Issue by GabrielBlink32** [CryptoMorin/XSeries#73]
**Description**
A class with make the same function that others but replace org.bukkit.Effect.FLAME for example to XEffect.FLAME.parseEffect()
Support for versions older than 1.8 will not be added. Some projects might not even support 1.8

**Comment by CryptoMorin** [comment]
Why? None of the [Effect](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Effect.java) names were changed.

**Comment by CryptoMorin** [comment]
This issue has been closed due to inactivity for a week.

**Comment by GabrielBlink32** [comment]
> Why? None of the [Effect](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Effect.java) names were changed.

The effect org.bukkit.Effect.FLAME was changed

**Comment by CryptoMorin** [comment]
> 
> 
> > Why? None of the [Effect](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Effect.java) names were changed.
> 
> The effect org.bukkit.Effect.FLAME was changed

I was unable to find such an effect named **FLAME** where did you find that in the source I mentioned above? However, there is a **MOBSPAWNER_FLAMES** which was never renamed.
Even if there was such a thing, it's extremely redundant to make a utility just for a single enum.
