### ISSUE TITLE
[XMaterial] - matchXMaterial(int id, byte data) doesnt work

### ISSUE THREAD

**Issue by IridiumLLC** [CryptoMorin/XSeries#78]
**Description**
```
    @Nonnull
    @Deprecated
    public static Optional<XMaterial> matchXMaterial(int id, byte data) {
        if (id < 0 || id > MAX_ID || data < 0) return Optional.empty();

        for (XMaterial materials : VALUES) {
            if (materials.data == data && materials.getId() == id) return Optional.of(materials);
        }
        return Optional.empty();
    }
```
Doesnt work on 1.13+ since you cant get the Id from the Material class using 1.13+ Materials.

One way around this would be to hard code the item id's into the XMaterial class, however this would be alot of work. Im happy to make a pull request to do this, but just wanted to make sure if that would be a good idea before I start, since it will take alot of work

**Comment by CryptoMorin** [comment]
Obviously yes? It doesn't work on 1.13+ for the reason you just said. This method is even deprecated. And no, adding a fake ID for each one of them is just extremely redundant. Why do you even want to do this? Literally the only way this is useful is if someone memorized the IDs, but why do that? Just use the name.

**Comment by IridiumLLC** [comment]
> Why do you even want to do this?
For schematics, obviously for the configs ill be using material names, but for the schematics block data is stored in id/bytes so I need a way to convert this to a Material

**Comment by CryptoMorin** [comment]
I'm assuming newer versions of WorldGuard isn't doing that since there is no ID for the new blocks. Or are they using a fake ID? (I can't seem to find it in the source code), but you're really slowing down the process by using this method. Here's the thing. Out of all the XSeries project, this is the most resource intense method next to the tesseract particle method.

**Comment by IridiumLLC** [comment]
Ye, this is only for pre 1.13 schematics that do this, so I guess its not that important.
