### ISSUE TITLE
Hey! About maven repository

### ISSUE THREAD

**Issue by portlek** [CryptoMorin/XSeries#8]
Hey, I want to ask a simple question. Do you have any maven repository for this project, If you have or not, I can sponsor for this project with my public repository? Why I want to a maven repository for this project is that we can use this unique project with ease.

**Comment by CryptoMorin** [comment]
I was going to add one. I'll see what I can do.

**Comment by CryptoMorin** [comment]
Check if this works:
```xml
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
            <version>5.0.0</version>
        </dependency>
```

**Comment by CryptoMorin** [comment]
Oh also can you confirm if this works. I'm not sure if it's synced with central.

**Comment by portlek** [comment]
Yes It's working.
