### ISSUE TITLE
Push new version to Maven Repository

### ISSUE THREAD

**Issue by IridiumLLC** [CryptoMorin/XSeries#87]
Can u version increment and update the maven repo. People keep complaining that they cant compile cuz the XBiome.getEnvironment() method doesnt exist

**Comment by CryptoMorin** [comment]
Please do not create issues for this. I'm currently away, so I can't. A hard way would be cloning the repository and installing it as a local repo without the GPG, staging plugins and everything else relating to the public repo.
If you can't do that, you'll have to wait. I'll be back in a few days.
