### ISSUE TITLE
[Material 1.16] - Issue

### ISSUE THREAD

**Issue by Cyb3r6host** [CryptoMorin/XSeries#99]
**Description**
Hey there i found a bug with 1.16 materials,
As it is known in 1.16 there are some materials like Material.CREEPER_SPAWN_EGG ect... 
When i try to access those materials with XMaterials.matchXmaterial all types of spawn eggs provide me the material of 
LEGACY_MONSTER_EGG
```java
System.out.println(XMaterial.matchXMaterial("CREEPER_SPAWN_EGG").get().parseMaterial());
//Output LEGACY_MONSTER_EGG
System.out.println(XMaterial.valueOf("creeper_spawn_egg").parseMaterial());
//Output Error No enum constant com.cryptomorin.xseries.XMaterial.creeper_spawn_egg
````

Also .parseMaterial() always return Legacy_ materials is this right ?

**Version**
1.16.5 Spigot 
Latest version of xSeries

**Comment by CryptoMorin** [comment]
I guess you didn't define `api-version` in your `plugin.yml`

**Comment by Cyb3r6host** [comment]
I have the ``api-version: 1.13`` included in my plugin.yml

**Comment by CryptoMorin** [comment]
I'm unable to reproduce it.
> System.out.println(XMaterial.matchXMaterial("CREEPER_SPAWN_EGG").get().parseMaterial());
Output: CREEPER_SPAWN_EGG
Using the same version.

**Comment by Cyb3r6host** [comment]
Hmmm strange i made a fresh test plugin with same version of XMaterial and it works fine but on the other plugin of mine  didnt work
